/*
 * JBoss, the OpenSource J2EE webOS
 *
 * Distributable under LGPL license.
 * See terms of license at gnu.org.
 */

package org.jboss.ejb.plugins.cmp.jdbc.mysql;

import java.lang.reflect.Method;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.ejb.CreateException;
import javax.ejb.DuplicateKeyException;
import javax.sql.DataSource;

import org.jboss.ejb.EntityEnterpriseContext;
import org.jboss.ejb.plugins.cmp.jdbc.bridge.JDBCFieldBridge;
import org.jboss.ejb.plugins.cmp.jdbc.bridge.JDBCCMPFieldBridge;
import org.jboss.ejb.plugins.cmp.jdbc.bridge.JDBCEntityBridge;
import org.jboss.ejb.plugins.keygenerator.KeyGenerator;
import org.jboss.ejb.plugins.cmp.jdbc.JDBCStoreManager;
import org.jboss.ejb.plugins.cmp.jdbc.JDBCCreateEntityCommand;
import org.jboss.ejb.plugins.cmp.jdbc.JDBCUtil;
import org.jboss.logging.Logger;

/**
 * MySQLCreateEntityCommand executes an INSERT INTO query.
 * The command uses MySQL specific API when fetching generated by MySQL key.
 * It works under JDK versions 1.3 and 1.4.
 * Also the command can safely substitute it's parent.
 *
 * @author <a href="mailto:loubyansky@hotmail.com">Alex Loubyansky</a>
 *
 * @version $Revision: 1.2 $
 */
public class MySQLCreateEntityCommand
   extends JDBCCreateEntityCommand
{

   /**
    * The method is the same as in the super class
    */
   public void init(JDBCStoreManager manager) {

      this.manager = manager;
      entity = manager.getEntityBridge();

      // Create the Log
      log = Logger.getLogger(
            this.getClass().getName() + 
            "." + 
            manager.getMetaData().getName());

      // set create allowed
      createAllowed = true;
      List fields = entity.getFields();
      for(Iterator iter = fields.iterator(); iter.hasNext(); ) {
         JDBCFieldBridge field = (JDBCFieldBridge)iter.next();
         if(field.isPrimaryKeyMember() && field.isReadOnly()) {
            createAllowed = false;
            break;
         }
      }
      
      if(createAllowed) {
         insertFields = getInsertFields();
         entityExistsSQL = createEntityExistsSQL();
         insertEntitySQL = createInsertEntitySQL();
         log.debug("Entity Exists SQL: " + entityExistsSQL);
         log.debug("Insert Entity SQL: " + insertEntitySQL);
      } else {
         log.debug("Create will not be allowed.");
      }
   }

   /**
    * This method is the same as in JDBCCreateEntityCommand under JDK 1.4
    */
   protected List getInsertFields() {
      List fields = entity.getFields();
      List insertFields = new ArrayList(fields.size());

      for(Iterator iter = fields.iterator(); iter.hasNext(); ) {
         JDBCFieldBridge field = (JDBCFieldBridge)iter.next();
         if(!field.isReadOnly()) {
            // only non-pk fields in case of jdbc30 key generation
            if( entity.isKeyDbGenerated() ) {
               if( !field.isPrimaryKeyMember() )
                  insertFields.add(field);
            } else {
               insertFields.add(field);
            }
         } 
      }
      return insertFields;
   }

   /**
    * This method is the same as in JDBCCreateEntityCommand under JDK 1.4
    */
   public Object execute(Method m,
                         Object[] args,
                         EntityEnterpriseContext ctx)
      throws CreateException {

      // primary key to return
      Object pk = null;

      if(!createAllowed) {
         throw new CreateException("Creation is not allowed because a " +
               "primary key field is read only.");
      }

      // set unknown pk if needed
      if( !entity.isKeyDbGenerated() ) {

         // set primary key if it is unknown
         setUnknownPk(ctx);

         pk = entity.extractPrimaryKeyFromInstance(ctx);
         log.debug("Create: pk="+pk);

         if(entityExists(pk)) {
            throw new DuplicateKeyException("Entity with primary key " + pk + 
               " already exists");
         }

         insertEntity(ctx);
      } else {
         insertEntity(ctx);
         pk = entity.extractPrimaryKeyFromInstance(ctx);
         log.debug("Created: pk="+pk);
      }

      return pk;         
   }

   /**
    * This method executes MySQL specific code in case of
    * primary key is db-generated
    */
   protected void insertEntity(EntityEnterpriseContext ctx)
      throws CreateException{

      Connection con = null;
      PreparedStatement ps = null;
      int rowsAffected  = 0;
      try {
         // get the connection
         DataSource dataSource = entity.getDataSource();
         con = dataSource.getConnection();
         
         // create the statement
         log.debug("Executing SQL: " + insertEntitySQL);
         ps = con.prepareStatement(insertEntitySQL);

         // set the parameters
         int index = 1;
         for(Iterator iter = insertFields.iterator(); iter.hasNext(); ) {
            JDBCFieldBridge field = (JDBCFieldBridge)iter.next();
            index = field.setInstanceParameters(ps, index, ctx);
         }

         // execute statement
         rowsAffected = ps.executeUpdate();
/* FIXME: this is temporarily commented!!!
          it won't work w/o it. but HEAD isn't compiled.
         if( entity.isKeyDbGenerated() ) {

            // cast to the wrapped statement
            org.jboss.resource.adapter.jdbc.WrappedStatement ws = 
               (org.jboss.resource.adapter.jdbc.WrappedStatement) ps;
            // fetch underlying statement and cast it to MySQL native
            com.mysql.jdbc.PreparedStatement mySqlStmt =
               (com.mysql.jdbc.PreparedStatement) ws.getUnderlyingStatement();

            ResultSet rs = mySqlStmt.getGeneratedKeys();
            Object pk = null;
            if( rs.next() ) {
               pk = rs.getObject( 1 );
            }

            if( pk == null ) {
               throw new Exception( "Primary key isn't generated." );
            }

            // write pk fields to the context
            for( Iterator iter = entity.getPrimaryKeyFields().iterator();
               iter.hasNext(); ) {
               JDBCCMPFieldBridge cmpField = (JDBCCMPFieldBridge) iter.next();
               cmpField.setInstanceValue( ctx, pk );
               break;
            }
         }
*/
      } catch(Exception e) {
         log.error("Could not create entity", e);
         throw new CreateException("Could not create entity:" + e);
      } finally {
         JDBCUtil.safeClose(ps);
         JDBCUtil.safeClose(con);
      }

      // check results
      if(rowsAffected != 1) {
         throw new CreateException("Insertion failed. Expected one " +
               "affected row: rowsAffected=" + rowsAffected +
               "id=" + ctx.getId());
      }
      log.debug("Rows affected = " + rowsAffected);

      // Mark the inserted fields as clean.
      for(Iterator iter = insertFields.iterator(); iter.hasNext(); ) {
         JDBCFieldBridge field = (JDBCFieldBridge)iter.next();
         field.setClean(ctx);
      }
   }
}
