

package org.tigris.scarab.om;

import java.util.List;
import java.util.HashMap;
import org.apache.torque.TorqueException;
import org.apache.torque.om.Persistent;

/** 
 * This class manages AttributeType objects.  
 * The skeleton for this class was autogenerated by Torque  * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public class AttributeTypeManager
    extends BaseAttributeTypeManager
{
    /**
     * Creates a new <code>AttributeTypeManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public AttributeTypeManager()
        throws TorqueException
    {
        super();
        setRegion(getClassName().replace('.', '_'));
        validFields = new HashMap();
        validFields.put(AttributeTypePeer.ATTRIBUTE_TYPE_ID, null);
    }

    protected Persistent putInstanceImpl(Persistent om)
        throws TorqueException
    {
        Persistent oldOm = super.putInstanceImpl(om);
        List listeners = (List)listenersMap
            .get(AttributeTypePeer.ATTRIBUTE_TYPE_ID);
        notifyListeners(listeners, oldOm, om);
        return oldOm;
    }


    public AttributeType getInstanceImpl()
    {
        return new AttributeType();
    }
}





