package org.tigris.scarab.om;

// JDK classes
import java.util.*;

// Turbine classes
import org.apache.turbine.services.db.om.*;
import org.apache.turbine.services.db.util.Criteria;
import org.apache.turbine.util.ObjectUtils;
import org.apache.turbine.util.StringUtils;
import org.apache.turbine.util.ParameterParser;

/** 
  * The skeleton for this class was autogenerated by Torque on:
  *
  * [Wed Feb 28 16:36:26 PST 2001]
  *
  * You should add additional methods to this class to meet the
  * application requirements.  This class will only be generated as
  * long as it does not already exist in the output directory.

  */
public class AttributeType 
    extends BaseAttributeType
    implements Persistent
{
    /* This interpretation of attribute type stretches its original 
       meaning so I will try to avoid it. - jdm
    protected boolean onePerModule;
    
    /**
     * Get the value of onePerModule.
     * @return value of onePerModule.
     * /
    public boolean isOnePerModule() 
    {
        return onePerModule;
    }
    
    /**
     * Set the value of onePerModule.
     * @param v  Value to assign to onePerModule.
     * /
    public void setOnePerModule(boolean  v) 
    {
        this.onePerModule = v;
    }
    */

}



