

package org.tigris.scarab.om;


import org.apache.torque.TorqueException;

/** 
 * This class manages PendingGroupUserRole objects.  
 * The skeleton for this class was autogenerated by Torque  * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public class PendingGroupUserRoleManager
    extends BasePendingGroupUserRoleManager
{
    /**
     * Creates a new <code>PendingGroupUserRoleManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public PendingGroupUserRoleManager()
        throws TorqueException
    {
        super();
    }

}





