

package org.tigris.scarab.om;

import java.util.List;
import java.util.HashMap;
import java.io.Serializable;

import org.apache.torque.TorqueException;
import org.apache.torque.om.Persistent;

/**
 * This class manages RAttributeAttributeGroup objects.  
 * The skeleton for this class was autogenerated by Torque  * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public class RAttributeAttributeGroupManager
    extends BaseRAttributeAttributeGroupManager
{
    /**
     * Creates a new <code>RAttributeAttributeGroupManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public RAttributeAttributeGroupManager()
        throws TorqueException
    {
        super();
        validFields = new HashMap();
        validFields.put(RAttributeAttributeGroupPeer.GROUP_ID, null);
    }

    protected Persistent putInstanceImpl(Persistent om)
        throws TorqueException
    {
        Persistent oldOm = super.putInstanceImpl(om);
        List listeners = (List)listenersMap
            .get(RAttributeAttributeGroupPeer.GROUP_ID);
        notifyListeners(listeners, oldOm, om);
        return oldOm;
    }

    protected RAttributeAttributeGroup getInstanceImpl()
    {
        return new RAttributeAttributeGroup();
    }
}





