package org.tigris.scarab.om;

// JDK classes
import java.util.*;

/** 
  * The skeleton for this class was autogenerated by Torque on:
  *
  * [Fri Apr 13 13:24:10 PDT 2001]
  *
  *  You should add additional methods to this class to meet the
  *  application requirements.  This class will only be generated as
  *  long as it does not already exist in the output directory.
  */
public class RModuleOptionPeer 
    extends org.tigris.scarab.om.BaseRModuleOptionPeer
{
}

