package org.tigris.scarab.om;

/* ================================================================
 * Copyright (c) 2000-2002 CollabNet.  All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 * 
 * 1. Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 * 
 * 2. Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution.
 * 
 * 3. The end-user documentation included with the redistribution, if
 * any, must include the following acknowlegement: "This product includes
 * software developed by Collab.Net <http://www.Collab.Net/>."
 * Alternately, this acknowlegement may appear in the software itself, if
 * and wherever such third-party acknowlegements normally appear.
 * 
 * 4. The hosted project names must not be used to endorse or promote
 * products derived from this software without prior written
 * permission. For written permission, please contact info@collab.net.
 * 
 * 5. Products derived from this software may not use the "Tigris" or 
 * "Scarab" names nor may "Tigris" or "Scarab" appear in their names without 
 * prior written permission of Collab.Net.
 * 
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL COLLAB.NET OR ITS CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
 * IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * ====================================================================
 * 
 * This software consists of voluntary contributions made by many
 * individuals on behalf of Collab.Net.
 */ 

// Turbine classes
import org.apache.torque.TorqueException;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.util.Criteria;
import com.workingdogs.village.Record;
import com.workingdogs.village.DataSetException;

// Scarab classes
import org.tigris.scarab.services.cache.ScarabCache;

/** 
  * The skeleton for this class was autogenerated by Torque on:
  *
  * [Wed Feb 28 16:36:26 PST 2001]
  *
  *  You should add additional methods to this class to meet the
  *  application requirements.  This class will only be generated as
  *  long as it does not already exist in the output directory.
  */
public class RModuleAttributePeer 
    extends org.tigris.scarab.om.BaseRModuleAttributePeer
{
    private static final String RMODULEATTRIBUTE_PEER = 
        "RModuleAttributePeer";
    private static final String RETRIEVE_BY_PK = 
        "retrieveByPK";

    private static final String COUNT = 
        "count(*)";

    /**
     * Adds count(*) to the select clause and returns the 
     * number of rows resulting from the given Criteria.  If the criteria will
     * lead to duplicate rows they will be counted.  
     *
     * @param crit a <code>Criteria</code> value
     * @return an <code>int</code> value
     * @exception TorqueException if an error occurs
     * @exception DataSetException if an error occurs
     */
    public static int count(Criteria crit)
        throws TorqueException, DataSetException
    {
        crit.addSelectColumn(COUNT);
        return ((Record)IssuePeer.doSelectVillageRecords(crit).get(0))
            .getValue(1).asInt();
    }

    /** 
     * Retrieve a single object by pk
     *
     * @param pk
     */
    public static RModuleAttribute retrieveByPK(ObjectKey pk)
        throws TorqueException
    {
        RModuleAttribute result = null;
        Object obj = ScarabCache.get(RMODULEATTRIBUTE_PEER, RETRIEVE_BY_PK, pk); 
        if (obj == null) 
        {        
            result = BaseRModuleAttributePeer.retrieveByPK(pk);
            ScarabCache.put(result, RMODULEATTRIBUTE_PEER, RETRIEVE_BY_PK, pk);
        }
        else 
        {
            result = (RModuleAttribute)obj;
        }
        return result;
    }
    
    public static void doDelete(RModuleAttribute rma) throws TorqueException
    {
        Criteria crit = new Criteria();
        crit.add(ConditionPeer.MODULE_ID, rma.getModuleId());
        crit.add(ConditionPeer.ISSUE_TYPE_ID, rma.getIssueTypeId());
        crit.add(ConditionPeer.ATTRIBUTE_ID, rma.getAttributeId());
        ConditionPeer.doDelete(crit);
        BaseTransitionPeer.doDelete(crit);
    }    
}

