package org.tigris.scarab.om;


import org.apache.turbine.services.db.om.Persistent;

/** 
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Jul 11 18:58:59 GMT-07:00 2001]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class RModuleUserAttribute 
    extends org.tigris.scarab.om.BaseRModuleUserAttribute
    implements Persistent
{
}
