package org.tigris.scarab.baseom.peer;

// JDK classes
import java.util.*;
import java.math.*;

// Village classes
import com.workingdogs.village.*;

// Turbine classes
import org.apache.turbine.om.peer.*;
import org.apache.turbine.util.*;
import org.apache.turbine.util.db.*;
import org.apache.turbine.util.db.map.*;
import org.apache.turbine.util.db.pool.DBConnection;

import org.tigris.scarab.baseom.ScarabIssueAttributeVote;

// Local classes
import org.tigris.scarab.baseom.map.*;
import org.tigris.scarab.baseom.*;

/** This class was autogenerated by GenerateMapBuilder on: Wed Feb 07 17:08:09 PST 2001 */
public abstract class BaseScarabIssueAttributeVotePeer extends BasePeer
{
    /** the mapbuilder for this class */
    private static final ScarabIssueAttributeVoteMapBuilder mapBuilder = 
        (ScarabIssueAttributeVoteMapBuilder)getMapBuilder(ScarabIssueAttributeVoteMapBuilder.CLASS_NAME);

    /** the table name for this class */
    public static final String TABLE_NAME = mapBuilder.getTable();

    /** the column name for the ISSUE_ID field */
    public static final String ISSUE_ID = mapBuilder.getScarabIssueAttributeVote_IssueId();
    /** the column name for the ATTRIBUTE_ID field */
    public static final String ATTRIBUTE_ID = mapBuilder.getScarabIssueAttributeVote_AttributeId();
    /** the column name for the USER_ID field */
    public static final String USER_ID = mapBuilder.getScarabIssueAttributeVote_UserId();
    /** the column name for the OPTION_ID field */
    public static final String OPTION_ID = mapBuilder.getScarabIssueAttributeVote_OptionId();

    /** number of columns for this peer */
    public static final int numColumns =  4;;

    /** Method to do inserts */
    public static Object doInsert( Criteria criteria ) throws Exception
    {
        criteria.setDbName(mapBuilder.getDatabaseMap().getName());
                                                                     return BasePeer.doInsert( criteria );
    }

    /** 
     * Method to do inserts.  This method is to be used during a transaction,
     * otherwise use the doInsert(Criteria) method.  It will take care of 
     * the connection details internally. 
     */
    public static Object doInsert( Criteria criteria, DBConnection dbCon ) throws Exception
    {
        criteria.setDbName(mapBuilder.getDatabaseMap().getName());
                                                                     return BasePeer.doInsert( criteria, dbCon );
    }

    /** Add all the columns needed to create a new object */
    public static void addSelectColumns (Criteria criteria) throws Exception
    {
            criteria.addSelectColumn( ISSUE_ID );
            criteria.addSelectColumn( ATTRIBUTE_ID );
            criteria.addSelectColumn( USER_ID );
            criteria.addSelectColumn( OPTION_ID );
        }


    /** Create a new object of type cls from a resultset row starting
      * from a specified offset.  This is done so that you can select
      * other rows than just those needed for this object.  You may
      * for example want to create two objects from the same row.
      */
    public static ScarabIssueAttributeVote row2Object (Record row, int offset, Class cls ) throws Exception
    {
        ScarabIssueAttributeVote obj = (ScarabIssueAttributeVote)cls.newInstance();
                                        obj.setIssueId(row.getValue(offset+0).asInt());
                                            obj.setAttributeId(row.getValue(offset+1).asInt());
                                            obj.setUserId(row.getValue(offset+2).asInt());
                                            obj.setOptionId(row.getValue(offset+3).asInt());
                                        obj.setModified(false);
                obj.setNew(false);
        return obj;
    }

    /** Method to do selects */
    public static Vector doSelect( Criteria criteria ) throws Exception
    {
        criteria.setDbName(mapBuilder.getDatabaseMap().getName());
        return doSelect (criteria,"org.tigris.scarab.baseom.ScarabIssueAttributeVote", null);
    }

    /** 
     * Method to do selects.  This method is to be used during a transaction,
     * otherwise use the doSelect(Criteria) method.  It will take care of 
     * the connection details internally. 
     */
    public static Vector doSelect( Criteria criteria, DBConnection dbCon ) throws Exception
    {
        criteria.setDbName(mapBuilder.getDatabaseMap().getName());
        return doSelect (criteria,"org.tigris.scarab.baseom.ScarabIssueAttributeVote", dbCon);
    }

    /** Method to do selects. The returned vector will have object
      * of className
      */
    public static Vector doSelect( Criteria criteria, String className, DBConnection dbCon) throws Exception
    {
        addSelectColumns ( criteria );

                                                             
        // BasePeer returns a Vector of Value (Village) arrays.  The array
        // order follows the order columns were placed in the Select clause.
        Vector rows = null;
        if (dbCon == null)
        {
            rows = BasePeer.doSelect(criteria);
        }
        else
        {
            rows = BasePeer.doSelect(criteria, dbCon);
        }
        Vector results = new Vector();

        // populate the object(s)
        for ( int i=0; i<rows.size(); i++ )
        {
            Record row = (Record)rows.elementAt(i);
            results.add (row2Object (row,1,Class.forName (className)));
         }
         return results;
    }

    /**
     * Method to do updates. 
     *
     * @param Criteria object containing data that is used to create the UPDATE statement.
     */
    public static void doUpdate(Criteria criteria) throws Exception
    {
        criteria.setDbName(mapBuilder.getDatabaseMap().getName());
        Criteria selectCriteria = new
            Criteria(mapBuilder.getDatabaseMap().getName(), 2);
                                selectCriteria.put( ISSUE_ID, criteria.remove(ISSUE_ID) );
                                         selectCriteria.put( ATTRIBUTE_ID, criteria.remove(ATTRIBUTE_ID) );
                                         selectCriteria.put( USER_ID, criteria.remove(USER_ID) );
                                              BasePeer.doUpdate( selectCriteria, criteria );
    }

    /** 
     * Method to do updates.  This method is to be used during a transaction,
     * otherwise use the doUpdate(Criteria) method.  It will take care of 
     * the connection details internally. 
     *
     * @param Criteria object containing data that is used to create the UPDATE statement.
     */
    public static void doUpdate(Criteria criteria, DBConnection dbCon) throws Exception
    {
        criteria.setDbName(mapBuilder.getDatabaseMap().getName());
        Criteria selectCriteria = new
            Criteria(mapBuilder.getDatabaseMap().getName(), 2);
                                selectCriteria.put( ISSUE_ID, criteria.remove(ISSUE_ID) );
                                         selectCriteria.put( ATTRIBUTE_ID, criteria.remove(ATTRIBUTE_ID) );
                                         selectCriteria.put( USER_ID, criteria.remove(USER_ID) );
                                              BasePeer.doUpdate( selectCriteria, criteria, dbCon );
     }

    /** 
     * Method to do deletes.
     *
     * @param Criteria object containing data that is used DELETE from database.
     */
     public static void doDelete(Criteria criteria) throws Exception
     {
         criteria.setDbName(mapBuilder.getDatabaseMap().getName());
                                                                      BasePeer.doDelete ( criteria );
     }

    /** 
     * Method to do deletes.  This method is to be used during a transaction,
     * otherwise use the doInsert(Criteria) method.  It will take care of 
     * the connection details internally. 
     *
     * @param Criteria object containing data that is used DELETE from database.
     */
     public static void doDelete(Criteria criteria, DBConnection dbCon) throws Exception
     {
         criteria.setDbName(mapBuilder.getDatabaseMap().getName());
                                                                      BasePeer.doDelete ( criteria, dbCon );
     }

    /** Method to do inserts */
    public static void doInsert( ScarabIssueAttributeVote obj ) throws Exception
    {
                doInsert(buildCriteria(obj));
                obj.setNew(false);
    }

    /**
     * @param obj the data object to update in the database.
     */
    public static void doUpdate(ScarabIssueAttributeVote obj) throws Exception
    {
        doUpdate(buildCriteria(obj));
    }
    /**
     * @param obj the data object to delete in the database.
     */
    public static void doDelete(ScarabIssueAttributeVote obj) throws Exception
    {
        doDelete(buildCriteria(obj));
    }

    /** 
     * Method to do inserts.  This method is to be used during a transaction,
     * otherwise use the doInsert(ScarabIssueAttributeVote) method.  It will take 
     * care of the connection details internally. 
     *
     * @param obj the data object to insert into the database.
     */
    public static void doInsert( ScarabIssueAttributeVote obj, DBConnection dbCon) throws Exception
    {
                doInsert(buildCriteria(obj), dbCon);
                obj.setNew(false);
    }

    /**
     * Method to do update.  This method is to be used during a transaction,
     * otherwise use the doUpdate(ScarabIssueAttributeVote) method.  It will take 
     * care of the connection details internally. 
     *
     * @param obj the data object to update in the database.
     */
    public static void doUpdate(ScarabIssueAttributeVote obj, DBConnection dbCon) throws Exception
    {
        doUpdate(buildCriteria(obj), dbCon);
    }
    /**
     * Method to delete.  This method is to be used during a transaction,
     * otherwise use the doDelete(ScarabIssueAttributeVote) method.  It will take 
     * care of the connection details internally. 
     *
     * @param obj the data object to delete in the database.
     */
    public static void doDelete(ScarabIssueAttributeVote obj, DBConnection dbCon) throws Exception
    {
        doDelete(buildCriteria(obj), dbCon);
    }

    /** Build a Criteria object from the data object for this peer */
    public static Criteria buildCriteria( ScarabIssueAttributeVote obj )
    {
        Criteria criteria = new Criteria();
                                criteria.add( ISSUE_ID, obj.getIssueId() );
                                criteria.add( ATTRIBUTE_ID, obj.getAttributeId() );
                                criteria.add( USER_ID, obj.getUserId() );
                                criteria.add( OPTION_ID, obj.getOptionId() );
                return criteria;
    }

    /** 
     * Retrieve a single object by pk where multiple PK's are separated
     * by colons
     *
     * @param int issue_id
     * @param int attribute_id
     * @param int user_id
     */
    public static ScarabIssueAttributeVote retrieveById(Object pkid) 
        throws Exception
    {
        StringTokenizer stok = new StringTokenizer((String)pkid, ":");
        if ( stok.countTokens() < 3 )
        {   
            throw new TurbineException(
                "id tokens did not match number of primary keys" );
        }
           int issue_id = Integer.parseInt(stok.nextToken());;
           int attribute_id = Integer.parseInt(stok.nextToken());;
           int user_id = Integer.parseInt(stok.nextToken());;

       return retrieveByPK(
             issue_id
              , attribute_id
              , user_id
              );
    }

    /** 
     * Retrieve a single object by pk
     *
     * @param int issue_id
     * @param int attribute_id
     * @param int user_id
     */
    public static ScarabIssueAttributeVote retrieveByPK(
                      int issue_id
                                      , int attribute_id
                                      , int user_id
                                         ) throws Exception
    {
        Criteria criteria = new Criteria();
                       if( issue_id > 0 )
                  criteria.add( ScarabIssueAttributeVotePeer.ISSUE_ID, issue_id );
                            if( attribute_id > 0 )
                  criteria.add( ScarabIssueAttributeVotePeer.ATTRIBUTE_ID, attribute_id );
                            if( user_id > 0 )
                  criteria.add( ScarabIssueAttributeVotePeer.USER_ID, user_id );
                          Vector ScarabIssueAttributeVoteVector = doSelect(criteria);
        if (ScarabIssueAttributeVoteVector.size() != 1)
        {
            throw new Exception("Failed to select one and only one row.");
        }
        else
        {
            return (ScarabIssueAttributeVote) ScarabIssueAttributeVoteVector.firstElement();
        }
    }


       
        
                       
     
          


   /**
    * selects a collection of ScarabIssueAttributeVote objects pre-filled with their
    * ScarabAttributeOption objects.
    */
    public static Vector doSelectJoinScarabAttributeOption(Criteria c)
        throws Exception
    {
         c.setDbName(mapBuilder.getDatabaseMap().getName());

        addSelectColumns(c);
        int offset = numColumns + 1;
        ScarabAttributeOptionPeer.addSelectColumns(c);

                                                                     
        Vector rows = BasePeer.doSelect(c);
        Vector results = new Vector();

        for (int i=0; i<rows.size(); i++)
        {
            ScarabIssueAttributeVote obj1 = 
                row2Object((com.workingdogs.village.Record)rows.elementAt(i),
                            1, Class.forName("org.tigris.scarab.baseom.ScarabIssueAttributeVote") );
            ScarabAttributeOption obj2 = ScarabAttributeOptionPeer
                .row2Object((com.workingdogs.village.Record)rows.elementAt(i),
                            offset, Class.forName("org.tigris.scarab.baseom.ScarabAttributeOption") );
            
            boolean newObject = true;
            for (int j=0; j<results.size(); j++)
            {
                ScarabIssueAttributeVote temp_obj1 = (ScarabIssueAttributeVote)results.elementAt(j);
                ScarabAttributeOption temp_obj2 = temp_obj1.getScarabAttributeOption();
                if ( temp_obj2.getPrimaryKey().equals(obj2.getPrimaryKey() ) )
                {
                    newObject = false;
                    temp_obj2.addScarabIssueAttributeVotes(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj2.initScarabIssueAttributeVotes();
                obj2.addScarabIssueAttributeVotes(obj1);
            }
            results.add(obj1);

        }

        return results;
    }
         
                                    
     
          


   /**
    * selects a collection of ScarabIssueAttributeVote objects pre-filled with their
    * ScarabIssueAttributeValue objects.
    */
    public static Vector doSelectJoinScarabIssueAttributeValue(Criteria c)
        throws Exception
    {
         c.setDbName(mapBuilder.getDatabaseMap().getName());

        addSelectColumns(c);
        int offset = numColumns + 1;
        ScarabIssueAttributeValuePeer.addSelectColumns(c);

                                                                     
        Vector rows = BasePeer.doSelect(c);
        Vector results = new Vector();

        for (int i=0; i<rows.size(); i++)
        {
            ScarabIssueAttributeVote obj1 = 
                row2Object((com.workingdogs.village.Record)rows.elementAt(i),
                            1, Class.forName("org.tigris.scarab.baseom.ScarabIssueAttributeVote") );
            ScarabIssueAttributeValue obj2 = ScarabIssueAttributeValuePeer
                .row2Object((com.workingdogs.village.Record)rows.elementAt(i),
                            offset, Class.forName("org.tigris.scarab.baseom.ScarabIssueAttributeValue") );
            
            boolean newObject = true;
            for (int j=0; j<results.size(); j++)
            {
                ScarabIssueAttributeVote temp_obj1 = (ScarabIssueAttributeVote)results.elementAt(j);
                ScarabIssueAttributeValue temp_obj2 = temp_obj1.getScarabIssueAttributeValue();
                if ( temp_obj2.getPrimaryKey().equals(obj2.getPrimaryKey() ) )
                {
                    newObject = false;
                    temp_obj2.addScarabIssueAttributeVotes(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj2.initScarabIssueAttributeVotes();
                obj2.addScarabIssueAttributeVotes(obj1);
            }
            results.add(obj1);

        }

        return results;
    }
         
                       
     
          


   /**
    * selects a collection of ScarabIssueAttributeVote objects pre-filled with their
    * TurbineUser objects.
    */
    public static Vector doSelectJoinTurbineUser(Criteria c)
        throws Exception
    {
         c.setDbName(mapBuilder.getDatabaseMap().getName());

        addSelectColumns(c);
        int offset = numColumns + 1;
        TurbineUserPeer.addSelectColumns(c);

                                                                     
        Vector rows = BasePeer.doSelect(c);
        Vector results = new Vector();

        for (int i=0; i<rows.size(); i++)
        {
            ScarabIssueAttributeVote obj1 = 
                row2Object((com.workingdogs.village.Record)rows.elementAt(i),
                            1, Class.forName("org.tigris.scarab.baseom.ScarabIssueAttributeVote") );
            TurbineUser obj2 = TurbineUserPeer
                .row2Object((com.workingdogs.village.Record)rows.elementAt(i),
                            offset, Class.forName("org.tigris.scarab.baseom.TurbineUser") );
            
            boolean newObject = true;
            for (int j=0; j<results.size(); j++)
            {
                ScarabIssueAttributeVote temp_obj1 = (ScarabIssueAttributeVote)results.elementAt(j);
                TurbineUser temp_obj2 = temp_obj1.getTurbineUser();
                if ( temp_obj2.getPrimaryKey().equals(obj2.getPrimaryKey() ) )
                {
                    newObject = false;
                    temp_obj2.addScarabIssueAttributeVotes(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj2.initScarabIssueAttributeVotes();
                obj2.addScarabIssueAttributeVotes(obj1);
            }
            results.add(obj1);

        }

        return results;
    }
    

  
  
     
                       
          


   /**
    * selects a collection of ScarabIssueAttributeVote objects pre-filled with 
    * all related objects.
    */
    public static Vector doSelectJoinAllExceptScarabAttributeOption(Criteria c) 
        throws Exception
    {
         c.setDbName(mapBuilder.getDatabaseMap().getName());

        addSelectColumns(c);
        int offset2 = numColumns + 1;
                    
                                      
                ScarabIssueAttributeValuePeer.addSelectColumns(c);
        int offset3 = offset2 + ScarabIssueAttributeValuePeer.numColumns;
                                          
                TurbineUserPeer.addSelectColumns(c);
        int offset4 = offset3 + TurbineUserPeer.numColumns;
                                                                                           
        Vector rows = BasePeer.doSelect(c);
        Vector results = new Vector();

        for (int i=0; i<rows.size(); i++)
        {
            ScarabIssueAttributeVote obj1 = 
                row2Object((com.workingdogs.village.Record)rows.elementAt(i),
                            1, Class.forName("org.tigris.scarab.baseom.ScarabIssueAttributeVote") );
                    
                                  
                                                                            
                        
                        ScarabIssueAttributeValue obj2 = ScarabIssueAttributeValuePeer
                .row2Object((com.workingdogs.village.Record)rows.elementAt(i),
                            offset2, Class.forName("org.tigris.scarab.baseom.ScarabIssueAttributeValue") );

            
             boolean  newObject = true;
            for (int j=0; j<results.size(); j++)
            {
                ScarabIssueAttributeVote temp_obj1 = (ScarabIssueAttributeVote)results.elementAt(j);
                ScarabIssueAttributeValue temp_obj2 = temp_obj1.getScarabIssueAttributeValue();
                if ( temp_obj2.getPrimaryKey().equals(obj2.getPrimaryKey() ) )
                {
                    newObject = false;
                    temp_obj2.addScarabIssueAttributeVotes(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj2.initScarabIssueAttributeVotes();
                obj2.addScarabIssueAttributeVotes(obj1);
            }
                        
                                                
                        
                        TurbineUser obj3 = TurbineUserPeer
                .row2Object((com.workingdogs.village.Record)rows.elementAt(i),
                            offset3, Class.forName("org.tigris.scarab.baseom.TurbineUser") );

            
             newObject = true;
            for (int j=0; j<results.size(); j++)
            {
                ScarabIssueAttributeVote temp_obj1 = (ScarabIssueAttributeVote)results.elementAt(j);
                TurbineUser temp_obj3 = temp_obj1.getTurbineUser();
                if ( temp_obj3.getPrimaryKey().equals(obj3.getPrimaryKey() ) )
                {
                    newObject = false;
                    temp_obj3.addScarabIssueAttributeVotes(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj3.initScarabIssueAttributeVotes();
                obj3.addScarabIssueAttributeVotes(obj1);
            }
                        results.add(obj1);

        }

        return results;
    }
 
     
                                    
          


   /**
    * selects a collection of ScarabIssueAttributeVote objects pre-filled with 
    * all related objects.
    */
    public static Vector doSelectJoinAllExceptScarabIssueAttributeValue(Criteria c) 
        throws Exception
    {
         c.setDbName(mapBuilder.getDatabaseMap().getName());

        addSelectColumns(c);
        int offset2 = numColumns + 1;
                    
                ScarabAttributeOptionPeer.addSelectColumns(c);
        int offset3 = offset2 + ScarabAttributeOptionPeer.numColumns;
                                          
                                      
                TurbineUserPeer.addSelectColumns(c);
        int offset4 = offset3 + TurbineUserPeer.numColumns;
                                                                                           
        Vector rows = BasePeer.doSelect(c);
        Vector results = new Vector();

        for (int i=0; i<rows.size(); i++)
        {
            ScarabIssueAttributeVote obj1 = 
                row2Object((com.workingdogs.village.Record)rows.elementAt(i),
                            1, Class.forName("org.tigris.scarab.baseom.ScarabIssueAttributeVote") );
                    
                                                
                        
                        ScarabAttributeOption obj2 = ScarabAttributeOptionPeer
                .row2Object((com.workingdogs.village.Record)rows.elementAt(i),
                            offset2, Class.forName("org.tigris.scarab.baseom.ScarabAttributeOption") );

            
             boolean  newObject = true;
            for (int j=0; j<results.size(); j++)
            {
                ScarabIssueAttributeVote temp_obj1 = (ScarabIssueAttributeVote)results.elementAt(j);
                ScarabAttributeOption temp_obj2 = temp_obj1.getScarabAttributeOption();
                if ( temp_obj2.getPrimaryKey().equals(obj2.getPrimaryKey() ) )
                {
                    newObject = false;
                    temp_obj2.addScarabIssueAttributeVotes(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj2.initScarabIssueAttributeVotes();
                obj2.addScarabIssueAttributeVotes(obj1);
            }
                        
                                  
                                                
                        
                        TurbineUser obj3 = TurbineUserPeer
                .row2Object((com.workingdogs.village.Record)rows.elementAt(i),
                            offset3, Class.forName("org.tigris.scarab.baseom.TurbineUser") );

            
             newObject = true;
            for (int j=0; j<results.size(); j++)
            {
                ScarabIssueAttributeVote temp_obj1 = (ScarabIssueAttributeVote)results.elementAt(j);
                TurbineUser temp_obj3 = temp_obj1.getTurbineUser();
                if ( temp_obj3.getPrimaryKey().equals(obj3.getPrimaryKey() ) )
                {
                    newObject = false;
                    temp_obj3.addScarabIssueAttributeVotes(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj3.initScarabIssueAttributeVotes();
                obj3.addScarabIssueAttributeVotes(obj1);
            }
                        results.add(obj1);

        }

        return results;
    }
 
     
                       
          


   /**
    * selects a collection of ScarabIssueAttributeVote objects pre-filled with 
    * all related objects.
    */
    public static Vector doSelectJoinAllExceptTurbineUser(Criteria c) 
        throws Exception
    {
         c.setDbName(mapBuilder.getDatabaseMap().getName());

        addSelectColumns(c);
        int offset2 = numColumns + 1;
                    
                ScarabAttributeOptionPeer.addSelectColumns(c);
        int offset3 = offset2 + ScarabAttributeOptionPeer.numColumns;
                                          
                ScarabIssueAttributeValuePeer.addSelectColumns(c);
        int offset4 = offset3 + ScarabIssueAttributeValuePeer.numColumns;
                                          
                                                                                       
        Vector rows = BasePeer.doSelect(c);
        Vector results = new Vector();

        for (int i=0; i<rows.size(); i++)
        {
            ScarabIssueAttributeVote obj1 = 
                row2Object((com.workingdogs.village.Record)rows.elementAt(i),
                            1, Class.forName("org.tigris.scarab.baseom.ScarabIssueAttributeVote") );
                    
                                                
                        
                        ScarabAttributeOption obj2 = ScarabAttributeOptionPeer
                .row2Object((com.workingdogs.village.Record)rows.elementAt(i),
                            offset2, Class.forName("org.tigris.scarab.baseom.ScarabAttributeOption") );

            
             boolean  newObject = true;
            for (int j=0; j<results.size(); j++)
            {
                ScarabIssueAttributeVote temp_obj1 = (ScarabIssueAttributeVote)results.elementAt(j);
                ScarabAttributeOption temp_obj2 = temp_obj1.getScarabAttributeOption();
                if ( temp_obj2.getPrimaryKey().equals(obj2.getPrimaryKey() ) )
                {
                    newObject = false;
                    temp_obj2.addScarabIssueAttributeVotes(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj2.initScarabIssueAttributeVotes();
                obj2.addScarabIssueAttributeVotes(obj1);
            }
                        
                                                                            
                        
                        ScarabIssueAttributeValue obj3 = ScarabIssueAttributeValuePeer
                .row2Object((com.workingdogs.village.Record)rows.elementAt(i),
                            offset3, Class.forName("org.tigris.scarab.baseom.ScarabIssueAttributeValue") );

            
             newObject = true;
            for (int j=0; j<results.size(); j++)
            {
                ScarabIssueAttributeVote temp_obj1 = (ScarabIssueAttributeVote)results.elementAt(j);
                ScarabIssueAttributeValue temp_obj3 = temp_obj1.getScarabIssueAttributeValue();
                if ( temp_obj3.getPrimaryKey().equals(obj3.getPrimaryKey() ) )
                {
                    newObject = false;
                    temp_obj3.addScarabIssueAttributeVotes(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj3.initScarabIssueAttributeVotes();
                obj3.addScarabIssueAttributeVotes(obj1);
            }
                        
                                  results.add(obj1);

        }

        return results;
    }
  


  
    /** 
     * Retrieve objects by fk
     *
     * @param int issue_id
     */
//    public static Vector retrieveByIssueId(int issue_id)
//    {
        
    
    /** 
     * Retrieve objects by fk
     *
     * @param int attribute_id
     */
//    public static Vector retrieveByAttributeId(int attribute_id)
//    {
        
    
    /** 
     * Retrieve objects by fk
     *
     * @param int user_id
     */
//    public static Vector retrieveByUserId(int user_id)
//    {
        
    
    /** 
     * Retrieve objects by fk
     *
     * @param int option_id
     */
//    public static Vector retrieveByOptionId(int option_id)
//    {
        
  
}








