package org.tigris.scarab.baseom.base;


// JDK classes
import java.util.*;
import java.math.*;

// Turbine classes
import org.apache.turbine.om.*;
import org.apache.turbine.om.peer.BasePeer;
import org.apache.turbine.util.db.Criteria;
import org.apache.turbine.util.ObjectUtils;
import org.apache.turbine.util.StringUtils;
import org.apache.turbine.util.ParameterParser;
import org.apache.turbine.util.Log;
import org.apache.turbine.util.db.pool.DBConnection;

import org.tigris.scarab.baseom.*;
import org.tigris.scarab.baseom.peer.*;

/** 
 * This class was autogenerated by Torque on:
 *
 * [Thu Feb 22 18:38:08 PST 2001]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to Transaction 
 */
public abstract class BaseTransaction extends BaseObject
{
    /** the value for the transaction_id field */
    private SimpleKey transaction_id;
    /** the value for the created_by field */
    private int created_by;
    /** the value for the created_date field */
    private Date created_date;


    /**
     * Get the TransactionId
     * @return SimpleKey
     */
     public SimpleKey getTransactionId()
     {
          return transaction_id;
     }

                            
    /**
     * Set the value of TransactionId
     */
     public void setTransactionId(SimpleKey v ) throws Exception
     {
  
       
        
                
          // update associated Activity
          if (collActivitys != null )
          {
              for (int i=0; i<collActivitys.size(); i++)
              {
                  ((Activity)collActivitys.get(i))
                      .setTransactionId(v);
              }
          }
       

         if ( !ObjectUtils.equals(this.transaction_id, v) )
        {
                       if (this.transaction_id == null)
            {
                this.transaction_id = v;
            }
            else
            {
                this.transaction_id.set(v);
            }
                      setModified(true);
        }
     }
    /**
     * Get the CreatedBy
     * @return int
     */
     public int getCreatedBy()
     {
          return created_by;
     }

        
    /**
     * Set the value of CreatedBy
     */
     public void setCreatedBy(int v ) 
     {
  
  

         if (this.created_by != v)
        {
                       this.created_by = v;
                      setModified(true);
        }
     }
    /**
     * Get the CreatedDate
     * @return Date
     */
     public Date getCreatedDate()
     {
          return created_date;
     }

        
    /**
     * Set the value of CreatedDate
     */
     public void setCreatedDate(Date v ) 
     {
  
  

         if ( !ObjectUtils.equals(this.created_date, v) )
        {
                       this.created_date = v;
                      setModified(true);
        }
     }

 
    
                
      
    /**
     * Collection to store aggregation of collActivitys
     */
    private Vector collActivitys;
    /**
     * Temporary storage of collActivitys to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
//    private Vector tempcollActivitys;

    public void initActivitys()
    {
        if (collActivitys == null)
            collActivitys = new Vector();
    }

    /**
     * Method called to associate a Activity object to this object
     * through the Activity foreign key attribute
     *
     * @param Activity l
     */
    public void addActivitys(Activity l) throws Exception
    {
        /*
        if (collActivitys == null)
        {
            if (tempcollActivitys == null)
            {
                tempcollActivitys = new Vector();
            }
            tempcollActivitys.add(l);
        }
        else
        {
            collActivitys.add(l);
        }
        */
        getActivitys().add(l);
        l.setTransaction((Transaction)this);
    }

    /**
     * The criteria used to select the current contents of collActivitys
     */
    private Criteria lastActivitysCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of 
     * getActivitys(new Criteria())
     */
    public Vector getActivitys() throws Exception
    {
        if (collActivitys == null)
        {
            collActivitys = getActivitys(new Criteria(10));
        }
        return collActivitys;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection. 
     * Otherwise if this Transaction is new, it will return
     * an empty collection; or if this Transaction has previously
     * been saved, it will retrieve related Activitys from storage.
     */
    public Vector getActivitys(Criteria criteria) throws Exception
    {
        if (collActivitys == null)
        {
            if ( isNew() ) 
            {
               collActivitys = new Vector();       
            } 
            else
            {
                   criteria.add(ActivityPeer.TRANSACTION_ID, getTransactionId() );               
                   collActivitys = ActivityPeer.doSelect(criteria);
            }
/*
            if (tempcollActivitys != null)
            {
                for (int i=0; i<tempcollActivitys.size(); i++)
                {
                    collActivitys.add(tempcollActivitys.get(i));
                }
                tempcollActivitys = null;
            }
*/
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(ActivityPeer.TRANSACTION_ID, getTransactionId() );               
               if ( !lastActivitysCriteria.equals(criteria)  )
            {
                collActivitys = ActivityPeer.doSelect(criteria);  
            }
        }
        lastActivitysCriteria = criteria; 

        return collActivitys;
    }
     

        
      
      
          
                    
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection. 
     * Otherwise if this Transaction is new, it will return
     * an empty collection; or if this Transaction has previously
     * been saved, it will retrieve related Activitys from storage.
     */
    public Vector getActivitysJoinIssue(Criteria criteria) 
        throws Exception
    {
        if (collActivitys == null)
        {
            if ( isNew() ) 
            {
               collActivitys = new Vector();       
            } 
            else
            {
                   criteria.add(ActivityPeer.TRANSACTION_ID, getTransactionId() );               
                   collActivitys = ActivityPeer.doSelectJoinIssue(criteria);
            }
            
            
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(ActivityPeer.TRANSACTION_ID, getTransactionId() );               
               if ( !lastActivitysCriteria.equals(criteria)  )
            {
                collActivitys = ActivityPeer.doSelectJoinIssue(criteria);
            }
        }
        lastActivitysCriteria = criteria; 

        return collActivitys;
    }
      
      
      
          
                    
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection. 
     * Otherwise if this Transaction is new, it will return
     * an empty collection; or if this Transaction has previously
     * been saved, it will retrieve related Activitys from storage.
     */
    public Vector getActivitysJoinAttribute(Criteria criteria) 
        throws Exception
    {
        if (collActivitys == null)
        {
            if ( isNew() ) 
            {
               collActivitys = new Vector();       
            } 
            else
            {
                   criteria.add(ActivityPeer.TRANSACTION_ID, getTransactionId() );               
                   collActivitys = ActivityPeer.doSelectJoinAttribute(criteria);
            }
            
            
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(ActivityPeer.TRANSACTION_ID, getTransactionId() );               
               if ( !lastActivitysCriteria.equals(criteria)  )
            {
                collActivitys = ActivityPeer.doSelectJoinAttribute(criteria);
            }
        }
        lastActivitysCriteria = criteria; 

        return collActivitys;
    }
      
      
         
          
                    
                
        
        
      



     
    
    private static Vector fieldNames_ = null;

    /**
     * Generate a list of field names.
     */
    public static Vector getFieldNames()
    {
      if (fieldNames_ == null)
      {
        fieldNames_ = new Vector();
            fieldNames_.add("TransactionId");
            fieldNames_.add("CreatedBy");
            fieldNames_.add("CreatedDate");
          }
      return fieldNames_;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.
     */
    public Object getByName(String name)
    {
            if (name.equals("TransactionId"))
	{
	  	    return getTransactionId();
	  	}
            if (name.equals("CreatedBy"))
	{
	  	    return new Integer(getCreatedBy());
	  	}
            if (name.equals("CreatedDate"))
	{
	  	    return getCreatedDate();
	  	}
            return null; 
    }
    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     */
    public Object getByPeerName(String name)
    {
            if (name == TransactionPeer.TRANSACTION_ID )
	    {
	  	    return getTransactionId();
	  	}
            if (name == TransactionPeer.CREATED_BY )
	    {
	  	    return new Integer(getCreatedBy());
	  	}
            if (name == TransactionPeer.CREATED_DATE )
	    {
	  	    return getCreatedDate();
	  	}
            return null; 
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     */
    public Object getByPosition(int pos)
    {
            if ( pos == 0 )
	{
	  	    return getTransactionId();
	  	}
            if ( pos == 1 )
	{
	  	    return new Integer(getCreatedBy());
	  	}
            if ( pos == 2 )
	{
	  	    return getCreatedDate();
	  	}
                return null; 
    }

     	

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     */
    public void save() throws Exception
    {
         DBConnection dbCon = null;
        try
        {
            dbCon = BasePeer.beginTransaction(
                TransactionPeer.getMapBuilder()
                .getDatabaseMap().getName());
            save(dbCon);
        }
        catch(Exception e)
        {
            BasePeer.rollBackTransaction(dbCon);
            throw e;
        }
        BasePeer.commitTransaction(dbCon);

     }

      // flag to prevent endless save loop, if this object is referenced
    // by another object which falls in this transaction.
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     */
    public void save(DBConnection dbCon) throws Exception
    {
        if (!alreadyInSave)
      {
        alreadyInSave = true;
          if (isModified())
        {
            if (isNew())
            {
                TransactionPeer.doInsert((Transaction)this, dbCon);
            }
            else
            {
                TransactionPeer.doUpdate((Transaction)this, dbCon);
                setNew(false);
            }
        }

                                    
                
          if (collActivitys != null )
          {
              for (int i=0; i<collActivitys.size(); i++)
              {
                  ((Activity)collActivitys.get(i)).save(dbCon);
              }
          }
                  alreadyInSave = false;
      }
      }

                                            
    /** 
     * Set the Id using pk values.
     *
     * @param SimpleKey transaction_id
     */
    public void setPrimaryKey(
     SimpleKey transaction_id
                ) throws Exception
    {
         setTransactionId(transaction_id);
    }
    



    /** 
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey() 
    {
        return getTransactionId();
    }

    /**
     * Makes a copy of this object.  
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public Transaction copy() throws Exception
    {
        Transaction copyObj = new Transaction();
        copyObj.setTransactionId(transaction_id);
        copyObj.setCreatedBy(created_by);
        copyObj.setCreatedDate(created_date);

                                
                
         List v = copyObj.getActivitys();
         for (int i=0; i<v.size(); i++)
         {
             ((BaseObject)v.get(i)).setNew(true);
         }
            
            
        copyObj.setTransactionId(null);
                return copyObj;
    }             
}

