package org.tigris.scarab.baseom.base;


// JDK classes
import java.util.*;
import java.math.*;

// Turbine classes
import org.apache.turbine.om.*;
import org.apache.turbine.om.peer.BasePeer;
import org.apache.turbine.util.db.Criteria;
import org.apache.turbine.util.ObjectUtils;
import org.apache.turbine.util.StringUtils;
import org.apache.turbine.util.ParameterParser;
import org.apache.turbine.util.Log;
import org.apache.turbine.util.db.pool.DBConnection;

import org.tigris.scarab.baseom.*;
import org.tigris.scarab.baseom.peer.*;

/** 
 * This class was autogenerated by Torque on:
 *
 * [Thu Feb 22 18:38:08 PST 2001]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to RModuleUserRole 
 */
public abstract class BaseRModuleUserRole extends BaseObject
{
    /** the value for the module_id field */
    private SimpleKey module_id;
    /** the value for the user_id field */
    private SimpleKey user_id;
    /** the value for the role_id field */
    private SimpleKey role_id;
    /** the value for the deleted field */
    private boolean deleted;


    /**
     * Get the ModuleId
     * @return SimpleKey
     */
     public SimpleKey getModuleId()
     {
          return module_id;
     }

            
    /**
     * Set the value of ModuleId
     */
     public void setModuleId(SimpleKey v ) throws Exception
     {
                  if ( aRModuleUser != null && !aRModuleUser.isNew())
        {
            throw new Exception("Can't set a foreign key directly after an "
                + " association is already made based on saved data.");
        }
  
  

         if ( !ObjectUtils.equals(this.module_id, v) )
        {
                       if (this.module_id == null)
            {
                this.module_id = v;
            }
            else
            {
                this.module_id.set(v);
            }
                      setModified(true);
        }
     }
    /**
     * Get the UserId
     * @return SimpleKey
     */
     public SimpleKey getUserId()
     {
          return user_id;
     }

            
    /**
     * Set the value of UserId
     */
     public void setUserId(SimpleKey v ) throws Exception
     {
                  if ( aRModuleUser != null && !aRModuleUser.isNew())
        {
            throw new Exception("Can't set a foreign key directly after an "
                + " association is already made based on saved data.");
        }
  
  

         if ( !ObjectUtils.equals(this.user_id, v) )
        {
                       if (this.user_id == null)
            {
                this.user_id = v;
            }
            else
            {
                this.user_id.set(v);
            }
                      setModified(true);
        }
     }
    /**
     * Get the RoleId
     * @return SimpleKey
     */
     public SimpleKey getRoleId()
     {
          return role_id;
     }

        
    /**
     * Set the value of RoleId
     */
     public void setRoleId(SimpleKey v ) 
     {
  
  

         if ( !ObjectUtils.equals(this.role_id, v) )
        {
                       if (this.role_id == null)
            {
                this.role_id = v;
            }
            else
            {
                this.role_id.set(v);
            }
                      setModified(true);
        }
     }
    /**
     * Get the Deleted
     * @return boolean
     */
     public boolean getDeleted()
     {
          return deleted;
     }

        
    /**
     * Set the value of Deleted
     */
     public void setDeleted(boolean v ) 
     {
  
  

         if (this.deleted != v)
        {
                       this.deleted = v;
                      setModified(true);
        }
     }

 
 
   
                    
   
   
    /**
     * Declares an association between this object and a RModuleUser object
     *
     * @param RModuleUser v
     */
    private RModuleUser aRModuleUser;
    public void setRModuleUser(RModuleUser v) throws Exception
    {
        aRModuleUser = null;
           setModuleId(v.getModuleId());
           setUserId(v.getUserId());
           aRModuleUser = v;
    }

                                
    public RModuleUser getRModuleUser() throws Exception
    {
        if ( aRModuleUser==null && (!ObjectUtils.equals(this.module_id, null) && !ObjectUtils.equals(this.user_id, null)) )
        {
            aRModuleUser = RModuleUserPeer.retrieveByPK(this.module_id, this.user_id);
            // The following can be used instead of the line above to
            // guarantee the related object contains a reference
            // to this object, but this level of coupling 
            // may be undesirable in many circumstances.
            // As it can lead to a db query with many results that may
            // never be used.  
            // RModuleUser obj = RModuleUserPeer.retrieveByPK(this.module_id, this.user_id);
            // obj.addRModuleUserRoles(this);
        }
        return aRModuleUser;
    }

    
        
    
    private static Vector fieldNames_ = null;

    /**
     * Generate a list of field names.
     */
    public static Vector getFieldNames()
    {
      if (fieldNames_ == null)
      {
        fieldNames_ = new Vector();
            fieldNames_.add("ModuleId");
            fieldNames_.add("UserId");
            fieldNames_.add("RoleId");
            fieldNames_.add("Deleted");
          }
      return fieldNames_;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.
     */
    public Object getByName(String name)
    {
            if (name.equals("ModuleId"))
	{
	  	    return getModuleId();
	  	}
            if (name.equals("UserId"))
	{
	  	    return getUserId();
	  	}
            if (name.equals("RoleId"))
	{
	  	    return getRoleId();
	  	}
            if (name.equals("Deleted"))
	{
	  	    return new Boolean(getDeleted());
	  	}
            return null; 
    }
    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     */
    public Object getByPeerName(String name)
    {
            if (name == RModuleUserRolePeer.MODULE_ID )
	    {
	  	    return getModuleId();
	  	}
            if (name == RModuleUserRolePeer.USER_ID )
	    {
	  	    return getUserId();
	  	}
            if (name == RModuleUserRolePeer.ROLE_ID )
	    {
	  	    return getRoleId();
	  	}
            if (name == RModuleUserRolePeer.DELETED )
	    {
	  	    return new Boolean(getDeleted());
	  	}
            return null; 
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     */
    public Object getByPosition(int pos)
    {
            if ( pos == 0 )
	{
	  	    return getModuleId();
	  	}
            if ( pos == 1 )
	{
	  	    return getUserId();
	  	}
            if ( pos == 2 )
	{
	  	    return getRoleId();
	  	}
            if ( pos == 3 )
	{
	  	    return new Boolean(getDeleted());
	  	}
                return null; 
    }

     	

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     */
    public void save() throws Exception
    {
         DBConnection dbCon = null;
        try
        {
            dbCon = BasePeer.beginTransaction(
                RModuleUserRolePeer.getMapBuilder()
                .getDatabaseMap().getName());
            save(dbCon);
        }
        catch(Exception e)
        {
            BasePeer.rollBackTransaction(dbCon);
            throw e;
        }
        BasePeer.commitTransaction(dbCon);

     }

      // flag to prevent endless save loop, if this object is referenced
    // by another object which falls in this transaction.
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     */
    public void save(DBConnection dbCon) throws Exception
    {
        if (!alreadyInSave)
      {
        alreadyInSave = true;
          if (isModified())
        {
            if (isNew())
            {
                RModuleUserRolePeer.doInsert((RModuleUserRole)this, dbCon);
            }
            else
            {
                RModuleUserRolePeer.doUpdate((RModuleUserRole)this, dbCon);
                setNew(false);
            }
        }

              alreadyInSave = false;
      }
      }

                                                            
    /** 
     * Set the Id using pk values.
     *
     * @param SimpleKey module_id
     * @param SimpleKey user_id
     * @param SimpleKey role_id
     */
    public void setPrimaryKey(
     SimpleKey module_id
            , SimpleKey user_id
            , SimpleKey role_id
                ) throws Exception
    {
         setModuleId(module_id);
         setUserId(user_id);
         setRoleId(role_id);
    }
    


    private final SimpleKey[] pks = new SimpleKey[3];
    private final ComboKey comboPK = new ComboKey(pks);
    /** 
     * Set the PrimaryKey with an ObjectKey
     */
    public void setPrimaryKey(ComboKey key) throws Exception
    {
        //if (key.getInternalObject() instanceof SimpleKey[])
        //{
            SimpleKey[] keys = (SimpleKey[])key.getInternalObject();
                    setModuleId(keys[0]);
                        setUserId(keys[1]);
                        setRoleId(keys[2]);
                
    }

    /** 
     * Set the PrimaryKey using a String.
     */
    public void setPrimaryKey(String key) throws Exception
    {
        int prevPos = 0;

                  int colonPos = key.indexOf(':', prevPos);
        setModuleId( new SimpleKey(key.substring(prevPos, colonPos)) );
        prevPos = colonPos + 1;
                     colonPos = key.indexOf(':', prevPos);
        setUserId( new SimpleKey(key.substring(prevPos, colonPos)) );
        prevPos = colonPos + 1;
                     colonPos = key.indexOf(':', prevPos);
        setRoleId( new SimpleKey(key.substring(prevPos, colonPos)) );
        prevPos = colonPos + 1;
                 }



    /** 
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey() 
    {
            pks[0] = getModuleId();
                    pks[1] = getUserId();
                    pks[2] = getRoleId();
                    return comboPK;
    }

    /**
     * Makes a copy of this object.  
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public RModuleUserRole copy() throws Exception
    {
        RModuleUserRole copyObj = new RModuleUserRole();
        copyObj.setModuleId(module_id);
        copyObj.setUserId(user_id);
        copyObj.setRoleId(role_id);
        copyObj.setDeleted(deleted);


            
        copyObj.setModuleId(null);
                
        copyObj.setUserId(null);
                
        copyObj.setRoleId(null);
            return copyObj;
    }             
}

