package org.tigris.scarab.baseom.base;


// JDK classes
import java.util.*;
import java.math.*;

// Turbine classes
import org.apache.turbine.om.*;
import org.apache.turbine.om.peer.BasePeer;
import org.apache.turbine.util.db.Criteria;
import org.apache.turbine.util.ObjectUtils;
import org.apache.turbine.util.StringUtils;
import org.apache.turbine.util.ParameterParser;
import org.apache.turbine.util.Log;
import org.apache.turbine.util.db.pool.DBConnection;

import org.tigris.scarab.baseom.*;
import org.tigris.scarab.baseom.peer.*;

/** 
 * This class was autogenerated by Torque on:
 *
 * [Thu Feb 22 18:38:08 PST 2001]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to AttributeClass 
 */
public abstract class BaseAttributeClass extends BaseObject
{
    /** the value for the attribute_class_id field */
    private SimpleKey attribute_class_id;
    /** the value for the attribute_class_name field */
    private String attribute_class_name;
    /** the value for the attribute_class_desc field */
    private String attribute_class_desc;
    /** the value for the java_class_name field */
    private String java_class_name;


    /**
     * Get the AttributeClassId
     * @return SimpleKey
     */
     public SimpleKey getAttributeClassId()
     {
          return attribute_class_id;
     }

                            
    /**
     * Set the value of AttributeClassId
     */
     public void setAttributeClassId(SimpleKey v ) throws Exception
     {
  
       
        
                
          // update associated AttributeType
          if (collAttributeTypes != null )
          {
              for (int i=0; i<collAttributeTypes.size(); i++)
              {
                  ((AttributeType)collAttributeTypes.get(i))
                      .setClassId(v);
              }
          }
       

         if ( !ObjectUtils.equals(this.attribute_class_id, v) )
        {
                       if (this.attribute_class_id == null)
            {
                this.attribute_class_id = v;
            }
            else
            {
                this.attribute_class_id.set(v);
            }
                      setModified(true);
        }
     }
    /**
     * Get the Name
     * @return String
     */
     public String getName()
     {
          return attribute_class_name;
     }

        
    /**
     * Set the value of Name
     */
     public void setName(String v ) 
     {
  
  

         if ( !ObjectUtils.equals(this.attribute_class_name, v) )
        {
                       this.attribute_class_name = v;
                      setModified(true);
        }
     }
    /**
     * Get the Desc
     * @return String
     */
     public String getDesc()
     {
          return attribute_class_desc;
     }

        
    /**
     * Set the value of Desc
     */
     public void setDesc(String v ) 
     {
  
  

         if ( !ObjectUtils.equals(this.attribute_class_desc, v) )
        {
                       this.attribute_class_desc = v;
                      setModified(true);
        }
     }
    /**
     * Get the JavaClassName
     * @return String
     */
     public String getJavaClassName()
     {
          return java_class_name;
     }

        
    /**
     * Set the value of JavaClassName
     */
     public void setJavaClassName(String v ) 
     {
  
  

         if ( !ObjectUtils.equals(this.java_class_name, v) )
        {
                       this.java_class_name = v;
                      setModified(true);
        }
     }

 
    
                
      
    /**
     * Collection to store aggregation of collAttributeTypes
     */
    private Vector collAttributeTypes;
    /**
     * Temporary storage of collAttributeTypes to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
//    private Vector tempcollAttributeTypes;

    public void initAttributeTypes()
    {
        if (collAttributeTypes == null)
            collAttributeTypes = new Vector();
    }

    /**
     * Method called to associate a AttributeType object to this object
     * through the AttributeType foreign key attribute
     *
     * @param AttributeType l
     */
    public void addAttributeTypes(AttributeType l) throws Exception
    {
        /*
        if (collAttributeTypes == null)
        {
            if (tempcollAttributeTypes == null)
            {
                tempcollAttributeTypes = new Vector();
            }
            tempcollAttributeTypes.add(l);
        }
        else
        {
            collAttributeTypes.add(l);
        }
        */
        getAttributeTypes().add(l);
        l.setAttributeClass((AttributeClass)this);
    }

    /**
     * The criteria used to select the current contents of collAttributeTypes
     */
    private Criteria lastAttributeTypesCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of 
     * getAttributeTypes(new Criteria())
     */
    public Vector getAttributeTypes() throws Exception
    {
        if (collAttributeTypes == null)
        {
            collAttributeTypes = getAttributeTypes(new Criteria(10));
        }
        return collAttributeTypes;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection. 
     * Otherwise if this AttributeClass is new, it will return
     * an empty collection; or if this AttributeClass has previously
     * been saved, it will retrieve related AttributeTypes from storage.
     */
    public Vector getAttributeTypes(Criteria criteria) throws Exception
    {
        if (collAttributeTypes == null)
        {
            if ( isNew() ) 
            {
               collAttributeTypes = new Vector();       
            } 
            else
            {
                   criteria.add(AttributeTypePeer.ATTRIBUTE_CLASS_ID, getAttributeClassId() );               
                   collAttributeTypes = AttributeTypePeer.doSelect(criteria);
            }
/*
            if (tempcollAttributeTypes != null)
            {
                for (int i=0; i<tempcollAttributeTypes.size(); i++)
                {
                    collAttributeTypes.add(tempcollAttributeTypes.get(i));
                }
                tempcollAttributeTypes = null;
            }
*/
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(AttributeTypePeer.ATTRIBUTE_CLASS_ID, getAttributeClassId() );               
               if ( !lastAttributeTypesCriteria.equals(criteria)  )
            {
                collAttributeTypes = AttributeTypePeer.doSelect(criteria);  
            }
        }
        lastAttributeTypesCriteria = criteria; 

        return collAttributeTypes;
    }
   

        
      
         
          
                    
                
        
        
      



     
    
    private static Vector fieldNames_ = null;

    /**
     * Generate a list of field names.
     */
    public static Vector getFieldNames()
    {
      if (fieldNames_ == null)
      {
        fieldNames_ = new Vector();
            fieldNames_.add("AttributeClassId");
            fieldNames_.add("Name");
            fieldNames_.add("Desc");
            fieldNames_.add("JavaClassName");
          }
      return fieldNames_;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.
     */
    public Object getByName(String name)
    {
            if (name.equals("AttributeClassId"))
	{
	  	    return getAttributeClassId();
	  	}
            if (name.equals("Name"))
	{
	  	    return getName();
	  	}
            if (name.equals("Desc"))
	{
	  	    return getDesc();
	  	}
            if (name.equals("JavaClassName"))
	{
	  	    return getJavaClassName();
	  	}
            return null; 
    }
    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     */
    public Object getByPeerName(String name)
    {
            if (name == AttributeClassPeer.ATTRIBUTE_CLASS_ID )
	    {
	  	    return getAttributeClassId();
	  	}
            if (name == AttributeClassPeer.ATTRIBUTE_CLASS_NAME )
	    {
	  	    return getName();
	  	}
            if (name == AttributeClassPeer.ATTRIBUTE_CLASS_DESC )
	    {
	  	    return getDesc();
	  	}
            if (name == AttributeClassPeer.JAVA_CLASS_NAME )
	    {
	  	    return getJavaClassName();
	  	}
            return null; 
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     */
    public Object getByPosition(int pos)
    {
            if ( pos == 0 )
	{
	  	    return getAttributeClassId();
	  	}
            if ( pos == 1 )
	{
	  	    return getName();
	  	}
            if ( pos == 2 )
	{
	  	    return getDesc();
	  	}
            if ( pos == 3 )
	{
	  	    return getJavaClassName();
	  	}
                return null; 
    }

     	

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     */
    public void save() throws Exception
    {
         DBConnection dbCon = null;
        try
        {
            dbCon = BasePeer.beginTransaction(
                AttributeClassPeer.getMapBuilder()
                .getDatabaseMap().getName());
            save(dbCon);
        }
        catch(Exception e)
        {
            BasePeer.rollBackTransaction(dbCon);
            throw e;
        }
        BasePeer.commitTransaction(dbCon);

     }

      // flag to prevent endless save loop, if this object is referenced
    // by another object which falls in this transaction.
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     */
    public void save(DBConnection dbCon) throws Exception
    {
        if (!alreadyInSave)
      {
        alreadyInSave = true;
          if (isModified())
        {
            if (isNew())
            {
                AttributeClassPeer.doInsert((AttributeClass)this, dbCon);
            }
            else
            {
                AttributeClassPeer.doUpdate((AttributeClass)this, dbCon);
                setNew(false);
            }
        }

                                    
                
          if (collAttributeTypes != null )
          {
              for (int i=0; i<collAttributeTypes.size(); i++)
              {
                  ((AttributeType)collAttributeTypes.get(i)).save(dbCon);
              }
          }
                  alreadyInSave = false;
      }
      }

                                                
    /** 
     * Set the Id using pk values.
     *
     * @param SimpleKey attribute_class_id
     */
    public void setPrimaryKey(
     SimpleKey attribute_class_id
                ) throws Exception
    {
         setAttributeClassId(attribute_class_id);
    }
    



    /** 
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey() 
    {
        return getAttributeClassId();
    }

    /**
     * Makes a copy of this object.  
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public AttributeClass copy() throws Exception
    {
        AttributeClass copyObj = new AttributeClass();
        copyObj.setAttributeClassId(attribute_class_id);
        copyObj.setName(attribute_class_name);
        copyObj.setDesc(attribute_class_desc);
        copyObj.setJavaClassName(java_class_name);

                                
                
         List v = copyObj.getAttributeTypes();
         for (int i=0; i<v.size(); i++)
         {
             ((BaseObject)v.get(i)).setNew(true);
         }
            
            
        copyObj.setAttributeClassId(null);
                    return copyObj;
    }             
}

