package org.tigris.scarab.baseom.base;


// JDK classes
import java.util.*;
import java.math.*;

// Turbine classes
import org.apache.turbine.om.*;
import org.apache.turbine.om.peer.BasePeer;
import org.apache.turbine.util.db.Criteria;
import org.apache.turbine.util.ObjectUtils;
import org.apache.turbine.util.StringUtils;
import org.apache.turbine.util.ParameterParser;
import org.apache.turbine.util.Log;
import org.apache.turbine.util.db.pool.DBConnection;

import org.tigris.scarab.baseom.*;
import org.tigris.scarab.baseom.peer.*;

/** 
 * This class was autogenerated by Torque on:
 *
 * [Thu Feb 22 18:38:08 PST 2001]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to Attribute 
 */
public abstract class BaseAttribute extends BaseObject
{
    /** the value for the attribute_id field */
    private SimpleKey attribute_id;
    /** the value for the attribute_name field */
    private String attribute_name;
    /** the value for the attribute_type_id field */
    private SimpleKey attribute_type_id;
    /** the value for the deleted field */
    private boolean deleted;


    /**
     * Get the AttributeId
     * @return SimpleKey
     */
     public SimpleKey getAttributeId()
     {
          return attribute_id;
     }

                            
    /**
     * Set the value of AttributeId
     */
     public void setAttributeId(SimpleKey v ) throws Exception
     {
  
       
        
                
          // update associated Activity
          if (collActivitys != null )
          {
              for (int i=0; i<collActivitys.size(); i++)
              {
                  ((Activity)collActivitys.get(i))
                      .setAttributeId(v);
              }
          }
            
        
                
          // update associated AttributeOption
          if (collAttributeOptions != null )
          {
              for (int i=0; i<collAttributeOptions.size(); i++)
              {
                  ((AttributeOption)collAttributeOptions.get(i))
                      .setAttributeId(v);
              }
          }
            
        
                
          // update associated AttributeValue
          if (collAttributeValues != null )
          {
              for (int i=0; i<collAttributeValues.size(); i++)
              {
                  ((AttributeValue)collAttributeValues.get(i))
                      .setAttributeId(v);
              }
          }
            
        
                
          // update associated RModuleAttribute
          if (collRModuleAttributes != null )
          {
              for (int i=0; i<collRModuleAttributes.size(); i++)
              {
                  ((RModuleAttribute)collRModuleAttributes.get(i))
                      .setAttributeId(v);
              }
          }
       

         if ( !ObjectUtils.equals(this.attribute_id, v) )
        {
                       if (this.attribute_id == null)
            {
                this.attribute_id = v;
            }
            else
            {
                this.attribute_id.set(v);
            }
                      setModified(true);
        }
     }
    /**
     * Get the Name
     * @return String
     */
     public String getName()
     {
          return attribute_name;
     }

        
    /**
     * Set the value of Name
     */
     public void setName(String v ) 
     {
  
  

         if ( !ObjectUtils.equals(this.attribute_name, v) )
        {
                       this.attribute_name = v;
                      setModified(true);
        }
     }
    /**
     * Get the TypeId
     * @return SimpleKey
     */
     public SimpleKey getTypeId()
     {
          return attribute_type_id;
     }

            
    /**
     * Set the value of TypeId
     */
     public void setTypeId(SimpleKey v ) throws Exception
     {
                  if ( aAttributeType != null && !aAttributeType.isNew())
        {
            throw new Exception("Can't set a foreign key directly after an "
                + " association is already made based on saved data.");
        }
  
  

         if ( !ObjectUtils.equals(this.attribute_type_id, v) )
        {
                       if (this.attribute_type_id == null)
            {
                this.attribute_type_id = v;
            }
            else
            {
                this.attribute_type_id.set(v);
            }
                      setModified(true);
        }
     }
    /**
     * Get the Deleted
     * @return boolean
     */
     public boolean getDeleted()
     {
          return deleted;
     }

        
    /**
     * Set the value of Deleted
     */
     public void setDeleted(boolean v ) 
     {
  
  

         if (this.deleted != v)
        {
                       this.deleted = v;
                      setModified(true);
        }
     }

 
 
   
             
   
   
    /**
     * Declares an association between this object and a AttributeType object
     *
     * @param AttributeType v
     */
    private AttributeType aAttributeType;
    public void setAttributeType(AttributeType v) throws Exception
    {
        aAttributeType = null;
           setTypeId(v.getAttributeTypeId());
           aAttributeType = v;
    }

                     
    public AttributeType getAttributeType() throws Exception
    {
        if ( aAttributeType==null && (!ObjectUtils.equals(this.attribute_type_id, null)) )
        {
            aAttributeType = AttributeTypePeer.retrieveByPK(this.attribute_type_id);
            // The following can be used instead of the line above to
            // guarantee the related object contains a reference
            // to this object, but this level of coupling 
            // may be undesirable in many circumstances.
            // As it can lead to a db query with many results that may
            // never be used.  
            // AttributeType obj = AttributeTypePeer.retrieveByPK(this.attribute_type_id);
            // obj.addAttributes(this);
        }
        return aAttributeType;
    }

    
                
      
    /**
     * Collection to store aggregation of collActivitys
     */
    private Vector collActivitys;
    /**
     * Temporary storage of collActivitys to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
//    private Vector tempcollActivitys;

    public void initActivitys()
    {
        if (collActivitys == null)
            collActivitys = new Vector();
    }

    /**
     * Method called to associate a Activity object to this object
     * through the Activity foreign key attribute
     *
     * @param Activity l
     */
    public void addActivitys(Activity l) throws Exception
    {
        /*
        if (collActivitys == null)
        {
            if (tempcollActivitys == null)
            {
                tempcollActivitys = new Vector();
            }
            tempcollActivitys.add(l);
        }
        else
        {
            collActivitys.add(l);
        }
        */
        getActivitys().add(l);
        l.setAttribute((Attribute)this);
    }

    /**
     * The criteria used to select the current contents of collActivitys
     */
    private Criteria lastActivitysCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of 
     * getActivitys(new Criteria())
     */
    public Vector getActivitys() throws Exception
    {
        if (collActivitys == null)
        {
            collActivitys = getActivitys(new Criteria(10));
        }
        return collActivitys;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection. 
     * Otherwise if this Attribute is new, it will return
     * an empty collection; or if this Attribute has previously
     * been saved, it will retrieve related Activitys from storage.
     */
    public Vector getActivitys(Criteria criteria) throws Exception
    {
        if (collActivitys == null)
        {
            if ( isNew() ) 
            {
               collActivitys = new Vector();       
            } 
            else
            {
                   criteria.add(ActivityPeer.ATTRIBUTE_ID, getAttributeId() );               
                   collActivitys = ActivityPeer.doSelect(criteria);
            }
/*
            if (tempcollActivitys != null)
            {
                for (int i=0; i<tempcollActivitys.size(); i++)
                {
                    collActivitys.add(tempcollActivitys.get(i));
                }
                tempcollActivitys = null;
            }
*/
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(ActivityPeer.ATTRIBUTE_ID, getAttributeId() );               
               if ( !lastActivitysCriteria.equals(criteria)  )
            {
                collActivitys = ActivityPeer.doSelect(criteria);  
            }
        }
        lastActivitysCriteria = criteria; 

        return collActivitys;
    }
     

        
      
      
          
                    
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection. 
     * Otherwise if this Attribute is new, it will return
     * an empty collection; or if this Attribute has previously
     * been saved, it will retrieve related Activitys from storage.
     */
    public Vector getActivitysJoinIssue(Criteria criteria) 
        throws Exception
    {
        if (collActivitys == null)
        {
            if ( isNew() ) 
            {
               collActivitys = new Vector();       
            } 
            else
            {
                   criteria.add(ActivityPeer.ATTRIBUTE_ID, getAttributeId() );               
                   collActivitys = ActivityPeer.doSelectJoinIssue(criteria);
            }
            
            
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(ActivityPeer.ATTRIBUTE_ID, getAttributeId() );               
               if ( !lastActivitysCriteria.equals(criteria)  )
            {
                collActivitys = ActivityPeer.doSelectJoinIssue(criteria);
            }
        }
        lastActivitysCriteria = criteria; 

        return collActivitys;
    }
      
      
         
          
                    
                
        
        
       
      
      
          
                    
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection. 
     * Otherwise if this Attribute is new, it will return
     * an empty collection; or if this Attribute has previously
     * been saved, it will retrieve related Activitys from storage.
     */
    public Vector getActivitysJoinTransaction(Criteria criteria) 
        throws Exception
    {
        if (collActivitys == null)
        {
            if ( isNew() ) 
            {
               collActivitys = new Vector();       
            } 
            else
            {
                   criteria.add(ActivityPeer.ATTRIBUTE_ID, getAttributeId() );               
                   collActivitys = ActivityPeer.doSelectJoinTransaction(criteria);
            }
            
            
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(ActivityPeer.ATTRIBUTE_ID, getAttributeId() );               
               if ( !lastActivitysCriteria.equals(criteria)  )
            {
                collActivitys = ActivityPeer.doSelectJoinTransaction(criteria);
            }
        }
        lastActivitysCriteria = criteria; 

        return collActivitys;
    }
     



             
      
    /**
     * Collection to store aggregation of collAttributeOptions
     */
    private Vector collAttributeOptions;
    /**
     * Temporary storage of collAttributeOptions to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
//    private Vector tempcollAttributeOptions;

    public void initAttributeOptions()
    {
        if (collAttributeOptions == null)
            collAttributeOptions = new Vector();
    }

    /**
     * Method called to associate a AttributeOption object to this object
     * through the AttributeOption foreign key attribute
     *
     * @param AttributeOption l
     */
    public void addAttributeOptions(AttributeOption l) throws Exception
    {
        /*
        if (collAttributeOptions == null)
        {
            if (tempcollAttributeOptions == null)
            {
                tempcollAttributeOptions = new Vector();
            }
            tempcollAttributeOptions.add(l);
        }
        else
        {
            collAttributeOptions.add(l);
        }
        */
        getAttributeOptions().add(l);
        l.setAttribute((Attribute)this);
    }

    /**
     * The criteria used to select the current contents of collAttributeOptions
     */
    private Criteria lastAttributeOptionsCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of 
     * getAttributeOptions(new Criteria())
     */
    public Vector getAttributeOptions() throws Exception
    {
        if (collAttributeOptions == null)
        {
            collAttributeOptions = getAttributeOptions(new Criteria(10));
        }
        return collAttributeOptions;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection. 
     * Otherwise if this Attribute is new, it will return
     * an empty collection; or if this Attribute has previously
     * been saved, it will retrieve related AttributeOptions from storage.
     */
    public Vector getAttributeOptions(Criteria criteria) throws Exception
    {
        if (collAttributeOptions == null)
        {
            if ( isNew() ) 
            {
               collAttributeOptions = new Vector();       
            } 
            else
            {
                   criteria.add(AttributeOptionPeer.ATTRIBUTE_ID, getAttributeId() );               
                   collAttributeOptions = AttributeOptionPeer.doSelect(criteria);
            }
/*
            if (tempcollAttributeOptions != null)
            {
                for (int i=0; i<tempcollAttributeOptions.size(); i++)
                {
                    collAttributeOptions.add(tempcollAttributeOptions.get(i));
                }
                tempcollAttributeOptions = null;
            }
*/
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(AttributeOptionPeer.ATTRIBUTE_ID, getAttributeId() );               
               if ( !lastAttributeOptionsCriteria.equals(criteria)  )
            {
                collAttributeOptions = AttributeOptionPeer.doSelect(criteria);  
            }
        }
        lastAttributeOptionsCriteria = criteria; 

        return collAttributeOptions;
    }
   

        
      
         
          
                    
                
        
        
      



             
      
    /**
     * Collection to store aggregation of collAttributeValues
     */
    private Vector collAttributeValues;
    /**
     * Temporary storage of collAttributeValues to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
//    private Vector tempcollAttributeValues;

    public void initAttributeValues()
    {
        if (collAttributeValues == null)
            collAttributeValues = new Vector();
    }

    /**
     * Method called to associate a AttributeValue object to this object
     * through the AttributeValue foreign key attribute
     *
     * @param AttributeValue l
     */
    public void addAttributeValues(AttributeValue l) throws Exception
    {
        /*
        if (collAttributeValues == null)
        {
            if (tempcollAttributeValues == null)
            {
                tempcollAttributeValues = new Vector();
            }
            tempcollAttributeValues.add(l);
        }
        else
        {
            collAttributeValues.add(l);
        }
        */
        getAttributeValues().add(l);
        l.setAttribute((Attribute)this);
    }

    /**
     * The criteria used to select the current contents of collAttributeValues
     */
    private Criteria lastAttributeValuesCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of 
     * getAttributeValues(new Criteria())
     */
    public Vector getAttributeValues() throws Exception
    {
        if (collAttributeValues == null)
        {
            collAttributeValues = getAttributeValues(new Criteria(10));
        }
        return collAttributeValues;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection. 
     * Otherwise if this Attribute is new, it will return
     * an empty collection; or if this Attribute has previously
     * been saved, it will retrieve related AttributeValues from storage.
     */
    public Vector getAttributeValues(Criteria criteria) throws Exception
    {
        if (collAttributeValues == null)
        {
            if ( isNew() ) 
            {
               collAttributeValues = new Vector();       
            } 
            else
            {
                   criteria.add(AttributeValuePeer.ATTRIBUTE_ID, getAttributeId() );               
                   collAttributeValues = AttributeValuePeer.doSelect(criteria);
            }
/*
            if (tempcollAttributeValues != null)
            {
                for (int i=0; i<tempcollAttributeValues.size(); i++)
                {
                    collAttributeValues.add(tempcollAttributeValues.get(i));
                }
                tempcollAttributeValues = null;
            }
*/
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(AttributeValuePeer.ATTRIBUTE_ID, getAttributeId() );               
               if ( !lastAttributeValuesCriteria.equals(criteria)  )
            {
                collAttributeValues = AttributeValuePeer.doSelect(criteria);  
            }
        }
        lastAttributeValuesCriteria = criteria; 

        return collAttributeValues;
    }
      

        
      
      
          
                    
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection. 
     * Otherwise if this Attribute is new, it will return
     * an empty collection; or if this Attribute has previously
     * been saved, it will retrieve related AttributeValues from storage.
     */
    public Vector getAttributeValuesJoinIssue(Criteria criteria) 
        throws Exception
    {
        if (collAttributeValues == null)
        {
            if ( isNew() ) 
            {
               collAttributeValues = new Vector();       
            } 
            else
            {
                   criteria.add(AttributeValuePeer.ATTRIBUTE_ID, getAttributeId() );               
                   collAttributeValues = AttributeValuePeer.doSelectJoinIssue(criteria);
            }
            
            
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(AttributeValuePeer.ATTRIBUTE_ID, getAttributeId() );               
               if ( !lastAttributeValuesCriteria.equals(criteria)  )
            {
                collAttributeValues = AttributeValuePeer.doSelectJoinIssue(criteria);
            }
        }
        lastAttributeValuesCriteria = criteria; 

        return collAttributeValues;
    }
      
      
         
          
                    
                
        
        
       
      
      
          
                    
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection. 
     * Otherwise if this Attribute is new, it will return
     * an empty collection; or if this Attribute has previously
     * been saved, it will retrieve related AttributeValues from storage.
     */
    public Vector getAttributeValuesJoinAttributeOption(Criteria criteria) 
        throws Exception
    {
        if (collAttributeValues == null)
        {
            if ( isNew() ) 
            {
               collAttributeValues = new Vector();       
            } 
            else
            {
                   criteria.add(AttributeValuePeer.ATTRIBUTE_ID, getAttributeId() );               
                   collAttributeValues = AttributeValuePeer.doSelectJoinAttributeOption(criteria);
            }
            
            
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(AttributeValuePeer.ATTRIBUTE_ID, getAttributeId() );               
               if ( !lastAttributeValuesCriteria.equals(criteria)  )
            {
                collAttributeValues = AttributeValuePeer.doSelectJoinAttributeOption(criteria);
            }
        }
        lastAttributeValuesCriteria = criteria; 

        return collAttributeValues;
    }
      
      
      
          
                    
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection. 
     * Otherwise if this Attribute is new, it will return
     * an empty collection; or if this Attribute has previously
     * been saved, it will retrieve related AttributeValues from storage.
     */
    public Vector getAttributeValuesJoinTurbineUser(Criteria criteria) 
        throws Exception
    {
        if (collAttributeValues == null)
        {
            if ( isNew() ) 
            {
               collAttributeValues = new Vector();       
            } 
            else
            {
                   criteria.add(AttributeValuePeer.ATTRIBUTE_ID, getAttributeId() );               
                   collAttributeValues = AttributeValuePeer.doSelectJoinTurbineUser(criteria);
            }
            
            
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(AttributeValuePeer.ATTRIBUTE_ID, getAttributeId() );               
               if ( !lastAttributeValuesCriteria.equals(criteria)  )
            {
                collAttributeValues = AttributeValuePeer.doSelectJoinTurbineUser(criteria);
            }
        }
        lastAttributeValuesCriteria = criteria; 

        return collAttributeValues;
    }
     



             
      
    /**
     * Collection to store aggregation of collRModuleAttributes
     */
    private Vector collRModuleAttributes;
    /**
     * Temporary storage of collRModuleAttributes to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
//    private Vector tempcollRModuleAttributes;

    public void initRModuleAttributes()
    {
        if (collRModuleAttributes == null)
            collRModuleAttributes = new Vector();
    }

    /**
     * Method called to associate a RModuleAttribute object to this object
     * through the RModuleAttribute foreign key attribute
     *
     * @param RModuleAttribute l
     */
    public void addRModuleAttributes(RModuleAttribute l) throws Exception
    {
        /*
        if (collRModuleAttributes == null)
        {
            if (tempcollRModuleAttributes == null)
            {
                tempcollRModuleAttributes = new Vector();
            }
            tempcollRModuleAttributes.add(l);
        }
        else
        {
            collRModuleAttributes.add(l);
        }
        */
        getRModuleAttributes().add(l);
        l.setAttribute((Attribute)this);
    }

    /**
     * The criteria used to select the current contents of collRModuleAttributes
     */
    private Criteria lastRModuleAttributesCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of 
     * getRModuleAttributes(new Criteria())
     */
    public Vector getRModuleAttributes() throws Exception
    {
        if (collRModuleAttributes == null)
        {
            collRModuleAttributes = getRModuleAttributes(new Criteria(10));
        }
        return collRModuleAttributes;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection. 
     * Otherwise if this Attribute is new, it will return
     * an empty collection; or if this Attribute has previously
     * been saved, it will retrieve related RModuleAttributes from storage.
     */
    public Vector getRModuleAttributes(Criteria criteria) throws Exception
    {
        if (collRModuleAttributes == null)
        {
            if ( isNew() ) 
            {
               collRModuleAttributes = new Vector();       
            } 
            else
            {
                   criteria.add(RModuleAttributePeer.ATTRIBUTE_ID, getAttributeId() );               
                   collRModuleAttributes = RModuleAttributePeer.doSelect(criteria);
            }
/*
            if (tempcollRModuleAttributes != null)
            {
                for (int i=0; i<tempcollRModuleAttributes.size(); i++)
                {
                    collRModuleAttributes.add(tempcollRModuleAttributes.get(i));
                }
                tempcollRModuleAttributes = null;
            }
*/
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(RModuleAttributePeer.ATTRIBUTE_ID, getAttributeId() );               
               if ( !lastRModuleAttributesCriteria.equals(criteria)  )
            {
                collRModuleAttributes = RModuleAttributePeer.doSelect(criteria);  
            }
        }
        lastRModuleAttributesCriteria = criteria; 

        return collRModuleAttributes;
    }
    

        
      
         
          
                    
                
        
        
       
      
      
          
                    
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection. 
     * Otherwise if this Attribute is new, it will return
     * an empty collection; or if this Attribute has previously
     * been saved, it will retrieve related RModuleAttributes from storage.
     */
    public Vector getRModuleAttributesJoinModule(Criteria criteria) 
        throws Exception
    {
        if (collRModuleAttributes == null)
        {
            if ( isNew() ) 
            {
               collRModuleAttributes = new Vector();       
            } 
            else
            {
                   criteria.add(RModuleAttributePeer.ATTRIBUTE_ID, getAttributeId() );               
                   collRModuleAttributes = RModuleAttributePeer.doSelectJoinModule(criteria);
            }
            
            
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(RModuleAttributePeer.ATTRIBUTE_ID, getAttributeId() );               
               if ( !lastRModuleAttributesCriteria.equals(criteria)  )
            {
                collRModuleAttributes = RModuleAttributePeer.doSelectJoinModule(criteria);
            }
        }
        lastRModuleAttributesCriteria = criteria; 

        return collRModuleAttributes;
    }
     



     
    
    private static Vector fieldNames_ = null;

    /**
     * Generate a list of field names.
     */
    public static Vector getFieldNames()
    {
      if (fieldNames_ == null)
      {
        fieldNames_ = new Vector();
            fieldNames_.add("AttributeId");
            fieldNames_.add("Name");
            fieldNames_.add("TypeId");
            fieldNames_.add("Deleted");
          }
      return fieldNames_;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.
     */
    public Object getByName(String name)
    {
            if (name.equals("AttributeId"))
	{
	  	    return getAttributeId();
	  	}
            if (name.equals("Name"))
	{
	  	    return getName();
	  	}
            if (name.equals("TypeId"))
	{
	  	    return getTypeId();
	  	}
            if (name.equals("Deleted"))
	{
	  	    return new Boolean(getDeleted());
	  	}
            return null; 
    }
    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     */
    public Object getByPeerName(String name)
    {
            if (name == AttributePeer.ATTRIBUTE_ID )
	    {
	  	    return getAttributeId();
	  	}
            if (name == AttributePeer.ATTRIBUTE_NAME )
	    {
	  	    return getName();
	  	}
            if (name == AttributePeer.ATTRIBUTE_TYPE_ID )
	    {
	  	    return getTypeId();
	  	}
            if (name == AttributePeer.DELETED )
	    {
	  	    return new Boolean(getDeleted());
	  	}
            return null; 
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     */
    public Object getByPosition(int pos)
    {
            if ( pos == 0 )
	{
	  	    return getAttributeId();
	  	}
            if ( pos == 1 )
	{
	  	    return getName();
	  	}
            if ( pos == 2 )
	{
	  	    return getTypeId();
	  	}
            if ( pos == 3 )
	{
	  	    return new Boolean(getDeleted());
	  	}
                return null; 
    }

     	

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     */
    public void save() throws Exception
    {
         DBConnection dbCon = null;
        try
        {
            dbCon = BasePeer.beginTransaction(
                AttributePeer.getMapBuilder()
                .getDatabaseMap().getName());
            save(dbCon);
        }
        catch(Exception e)
        {
            BasePeer.rollBackTransaction(dbCon);
            throw e;
        }
        BasePeer.commitTransaction(dbCon);

     }

      // flag to prevent endless save loop, if this object is referenced
    // by another object which falls in this transaction.
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     */
    public void save(DBConnection dbCon) throws Exception
    {
        if (!alreadyInSave)
      {
        alreadyInSave = true;
          if (isModified())
        {
            if (isNew())
            {
                AttributePeer.doInsert((Attribute)this, dbCon);
            }
            else
            {
                AttributePeer.doUpdate((Attribute)this, dbCon);
                setNew(false);
            }
        }

                                    
                
          if (collActivitys != null )
          {
              for (int i=0; i<collActivitys.size(); i++)
              {
                  ((Activity)collActivitys.get(i)).save(dbCon);
              }
          }
                                        
                
          if (collAttributeOptions != null )
          {
              for (int i=0; i<collAttributeOptions.size(); i++)
              {
                  ((AttributeOption)collAttributeOptions.get(i)).save(dbCon);
              }
          }
                                        
                
          if (collAttributeValues != null )
          {
              for (int i=0; i<collAttributeValues.size(); i++)
              {
                  ((AttributeValue)collAttributeValues.get(i)).save(dbCon);
              }
          }
                                        
                
          if (collRModuleAttributes != null )
          {
              for (int i=0; i<collRModuleAttributes.size(); i++)
              {
                  ((RModuleAttribute)collRModuleAttributes.get(i)).save(dbCon);
              }
          }
                  alreadyInSave = false;
      }
      }

                                                
    /** 
     * Set the Id using pk values.
     *
     * @param SimpleKey attribute_id
     */
    public void setPrimaryKey(
     SimpleKey attribute_id
                ) throws Exception
    {
         setAttributeId(attribute_id);
    }
    



    /** 
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey() 
    {
        return getAttributeId();
    }

    /**
     * Makes a copy of this object.  
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public Attribute copy() throws Exception
    {
        Attribute copyObj = new Attribute();
        copyObj.setAttributeId(attribute_id);
        copyObj.setName(attribute_name);
        copyObj.setTypeId(attribute_type_id);
        copyObj.setDeleted(deleted);

                                
                
         List v = copyObj.getActivitys();
         for (int i=0; i<v.size(); i++)
         {
             ((BaseObject)v.get(i)).setNew(true);
         }
                                            
                
         v = copyObj.getAttributeOptions();
         for (int i=0; i<v.size(); i++)
         {
             ((BaseObject)v.get(i)).setNew(true);
         }
                                            
                
         v = copyObj.getAttributeValues();
         for (int i=0; i<v.size(); i++)
         {
             ((BaseObject)v.get(i)).setNew(true);
         }
                                            
                
         v = copyObj.getRModuleAttributes();
         for (int i=0; i<v.size(); i++)
         {
             ((BaseObject)v.get(i)).setNew(true);
         }
            
            
        copyObj.setAttributeId(null);
                    return copyObj;
    }             
}

