/*
 * Adds another set of indices on the SCARAB_ISSUE_ATTRIBUTE_VALUE table
 * that is useful when self-joining on the ISSUE_ID for search criteria
 * involving multiple attributes
 * Adding similar indices to the SCARAB_ACTIVITY table as well.
 * 
 * Created By: John McNally
 */

CREATE INDEX IX_AV_ISSUE_OPTION_DEL ON 
    SCARAB_ISSUE_ATTRIBUTE_VALUE (ISSUE_ID, OPTION_ID, DELETED);
CREATE INDEX IX_AV_ISSUE_USER_DEL ON 
    SCARAB_ISSUE_ATTRIBUTE_VALUE (ISSUE_ID, USER_ID, DELETED);
CREATE INDEX IX_AV_ISSUE_INT_DEL ON 
    SCARAB_ISSUE_ATTRIBUTE_VALUE (ISSUE_ID, NUMERIC_VALUE, DELETED);

CREATE INDEX IX_ISSUE_NEW_OPTION ON 
    SCARAB_ACTIVITY (ISSUE_ID, NEW_OPTION_ID);
CREATE INDEX IX_ISSUE_NEW_USER ON 
    SCARAB_ACTIVITY (ISSUE_ID, NEW_USER_ID);
