@echo off
echo Drop Scarab database...
mysqladmin --force drop scarab

echo Create Scarab database...
mysqladmin --force create scarab

echo Importing mysql-scarab.sql...
mysql scarab < mysql-scarab.sql

echo Importing mysql-turbine.sql...
mysql scarab < mysql-turbine.sql

echo Importing mysql-turbine-scheduler.sql...
mysql scarab < mysql-turbine-scheduler.sql

echo Importing mysql-id-table-schema.sql...
mysql scarab < mysql-id-table-schema.sql

echo Importing mysql-turbine-id-table-init.sql...
mysql scarab < mysql-turbine-id-table-init.sql

echo Importing mysql-scarab-id-table-init.sql...
mysql scarab < mysql-scarab-id-table-init.sql

echo Importing mysql-scarab-required-data.sql...
mysql scarab < mysql-scarab-required-data.sql

echo Importing mysql-scarab-default-data.sql...
mysql scarab < mysql-scarab-default-data.sql

echo Importing mysql-scarab-security.sql...
mysql scarab < mysql-scarab-security.sql

echo Importing mysql-scarab-sample-data.sql...
mysql scarab < mysql-scarab-sample-data.sql
