

    

CREATE TABLE SCARAB_ACTIVITY (
        ISSUE_ID INTEGER  NOT NULL,
        ATTRIBUTE_ID INTEGER  NOT NULL,
        TRANSACTION_ID INTEGER  NOT NULL,
        OLD_VALUE VARCHAR (255) ,
        NEW_VALUE VARCHAR (255) ,
        FOREIGN KEY (ISSUE_ID) REFERENCES SCARAB_ISSUE (ISSUE_ID),
        FOREIGN KEY (ATTRIBUTE_ID) REFERENCES SCARAB_ATTRIBUTE (ATTRIBUTE_ID),
        FOREIGN KEY (TRANSACTION_ID) REFERENCES SCARAB_TRANSACTION (TRANSACTION_ID),
        PRIMARY KEY (ISSUE_ID,ATTRIBUTE_ID,TRANSACTION_ID)
);


    

CREATE TABLE SCARAB_ATTACHMENT (
        ATTACHMENT_ID INTEGER  NOT NULL,
        ISSUE_ID INTEGER  ,
        ATTACHMENT_TYPE_ID INTEGER  ,
        ATTACHMENT_NAME VARCHAR (255) ,
        ATTACHMENT_DATA BLOB ,
        ATTACHMENT_FILE_PATH VARCHAR (255) ,
        ATTACHMENT_MIME_TYPE VARCHAR (25) ,
        MODIFIED_BY INTEGER  ,
        CREATED_BY INTEGER  ,
        MODIFIED_DATE DATE  ,
        CREATED_DATE DATE  ,
        DELETED VARCHAR (1) ,
        FOREIGN KEY (ISSUE_ID) REFERENCES SCARAB_ISSUE (ISSUE_ID),
        FOREIGN KEY (ATTACHMENT_TYPE_ID) REFERENCES SCARAB_ATTACHMENT_TYPE (ATTACHMENT_TYPE_ID),
        PRIMARY KEY (ATTACHMENT_ID)
);


    

CREATE TABLE SCARAB_ATTACHMENT_TYPE (
        ATTACHMENT_TYPE_ID INTEGER  NOT NULL,
        ATTACHMENT_TYPE_NAME VARCHAR (255)  ,
        PRIMARY KEY (ATTACHMENT_TYPE_ID)
);


    

CREATE TABLE SCARAB_ATTRIBUTE (
        ATTRIBUTE_ID INTEGER  NOT NULL,
        ATTRIBUTE_NAME VARCHAR (255) ,
        ATTRIBUTE_TYPE_ID INTEGER  ,
        DELETED VARCHAR (1) ,
        FOREIGN KEY (ATTRIBUTE_TYPE_ID) REFERENCES SCARAB_ATTRIBUTE_TYPE (ATTRIBUTE_TYPE_ID),
        PRIMARY KEY (ATTRIBUTE_ID)
);


    

CREATE TABLE SCARAB_ATTRIBUTE_CLASS (
        ATTRIBUTE_CLASS_ID INTEGER  NOT NULL,
        ATTRIBUTE_CLASS_NAME VARCHAR (255) ,
        ATTRIBUTE_CLASS_DESC VARCHAR (255) ,
        JAVA_CLASS_NAME VARCHAR (255) ,
        PRIMARY KEY (ATTRIBUTE_CLASS_ID)
);


    

CREATE TABLE SCARAB_ATTRIBUTE_OPTION (
        OPTION_ID INTEGER  NOT NULL,
        ATTRIBUTE_ID INTEGER  ,
        DISPLAY_VALUE VARCHAR (255) ,
        NUMERIC_VALUE INTEGER  ,
        FOREIGN KEY (ATTRIBUTE_ID) REFERENCES SCARAB_ATTRIBUTE (ATTRIBUTE_ID),
        PRIMARY KEY (OPTION_ID)
);


    

CREATE TABLE SCARAB_ATTRIBUTE_TYPE (
        ATTRIBUTE_TYPE_ID INTEGER  NOT NULL,
        ATTRIBUTE_CLASS_ID INTEGER  ,
        ATTRIBUTE_TYPE_NAME VARCHAR (255) ,
        JAVA_CLASS_NAME VARCHAR (255) ,
        FOREIGN KEY (ATTRIBUTE_CLASS_ID) REFERENCES SCARAB_ATTRIBUTE_CLASS (ATTRIBUTE_CLASS_ID),
        PRIMARY KEY (ATTRIBUTE_TYPE_ID)
);


    

CREATE TABLE SCARAB_DEPEND (
        OBSERVED_ID INTEGER  NOT NULL,
        OBSERVER_ID INTEGER  NOT NULL,
        DEPEND_TYPE_ID INTEGER  ,
        DELETED VARCHAR (1) ,
        FOREIGN KEY (OBSERVED_ID) REFERENCES SCARAB_ISSUE (ISSUE_ID),
        FOREIGN KEY (OBSERVER_ID) REFERENCES SCARAB_ISSUE (ISSUE_ID),
        FOREIGN KEY (DEPEND_TYPE_ID) REFERENCES SCARAB_DEPEND_TYPE (DEPEND_TYPE_ID),
        PRIMARY KEY (OBSERVED_ID,OBSERVER_ID)
);


    

CREATE TABLE SCARAB_DEPEND_TYPE (
        DEPEND_TYPE_ID INTEGER  NOT NULL,
        DEPEND_TYPE_NAME VARCHAR (100) ,
        PRIMARY KEY (DEPEND_TYPE_ID)
);


    

CREATE TABLE SCARAB_ISSUE (
        ISSUE_ID INTEGER  NOT NULL,
        MODULE_ID INTEGER  ,
        MODIFIED_BY INTEGER  ,
        CREATED_BY INTEGER  ,
        MODIFIED_DATE DATE  ,
        CREATED_DATE DATE  ,
        DELETED VARCHAR (1) ,
        FOREIGN KEY (MODULE_ID) REFERENCES SCARAB_MODULE (MODULE_ID),
        PRIMARY KEY (ISSUE_ID)
);


    

CREATE TABLE SCARAB_ISSUE_ATTRIBUTE_VALUE (
        ISSUE_ID INTEGER  NOT NULL,
        ATTRIBUTE_ID INTEGER  NOT NULL,
        OPTION_ID INTEGER  ,
        USER_ID INTEGER  ,
        VALUE VARCHAR (255) ,
        DELETED VARCHAR (1) ,
        FOREIGN KEY (ISSUE_ID) REFERENCES SCARAB_ISSUE (ISSUE_ID),
        FOREIGN KEY (ATTRIBUTE_ID) REFERENCES SCARAB_ATTRIBUTE (ATTRIBUTE_ID),
        FOREIGN KEY (OPTION_ID) REFERENCES SCARAB_ATTRIBUTE_OPTION (OPTION_ID),
        PRIMARY KEY (ISSUE_ID,ATTRIBUTE_ID)
);


    

CREATE TABLE SCARAB_MODIFICATION (
        TABLE_ID INTEGER  NOT NULL,
        COLUMN_ID INTEGER  NOT NULL,
        MODIFIED_BY INTEGER  ,
        CREATED_BY INTEGER  ,
        MODIFIED_DATE DATE  ,
        CREATED_DATE DATE  ,
        PRIMARY KEY (TABLE_ID,COLUMN_ID)
);


    

CREATE TABLE SCARAB_MODULE (
        MODULE_ID INTEGER  NOT NULL,
        MODULE_NAME VARCHAR (255) ,
        MODULE_DESCRIPTION VARCHAR (255) ,
        MODULE_URL VARCHAR (255) ,
        PARENT_ID INTEGER  ,
        OWNER_ID INTEGER  ,
        QA_CONTACT_ID INTEGER  ,
        DELETED VARCHAR (1) ,
        PRIMARY KEY (MODULE_ID)
);


    

CREATE TABLE SCARAB_R_MODULE_ATTRIBUTE (
        ATTRIBUTE_ID INTEGER  NOT NULL,
        MODULE_ID INTEGER  NOT NULL,
        DELETED VARCHAR (1) ,
        FOREIGN KEY (ATTRIBUTE_ID) REFERENCES SCARAB_ATTRIBUTE (ATTRIBUTE_ID),
        FOREIGN KEY (MODULE_ID) REFERENCES SCARAB_MODULE (MODULE_ID),
        PRIMARY KEY (ATTRIBUTE_ID,MODULE_ID)
);


    

CREATE TABLE SCARAB_R_MODULE_USER (
        MODULE_ID INTEGER  NOT NULL,
        USER_ID INTEGER  NOT NULL,
        DELETED VARCHAR (1) ,
        FOREIGN KEY (MODULE_ID) REFERENCES SCARAB_MODULE (MODULE_ID),
        PRIMARY KEY (MODULE_ID,USER_ID)
);


    

CREATE TABLE SCARAB_R_MODULE_USER_ROLE (
        MODULE_ID INTEGER  NOT NULL,
        USER_ID INTEGER  NOT NULL,
        ROLE_ID INTEGER  NOT NULL,
        DELETED VARCHAR (1) ,
        FOREIGN KEY (MODULE_ID, USER_ID) REFERENCES SCARAB_R_MODULE_USER (MODULE_ID, USER_ID),
        PRIMARY KEY (MODULE_ID,USER_ID,ROLE_ID)
);


    

CREATE TABLE SCARAB_TRANSACTION (
        TRANSACTION_ID INTEGER  NOT NULL,
        CREATED_BY INTEGER  ,
        CREATED_DATE DATE  ,
        PRIMARY KEY (TRANSACTION_ID)
);


    

CREATE TABLE SCARAB_ISSUE_ATTRIBUTE_VOTE (
        ISSUE_ID INTEGER  NOT NULL,
        ATTRIBUTE_ID INTEGER  NOT NULL,
        USER_ID INTEGER  NOT NULL,
        OPTION_ID INTEGER  ,
        FOREIGN KEY (OPTION_ID) REFERENCES SCARAB_ATTRIBUTE_OPTION (OPTION_ID),
        FOREIGN KEY (ISSUE_ID, ATTRIBUTE_ID) REFERENCES SCARAB_ISSUE_ATTRIBUTE_VALUE (ISSUE_ID, ATTRIBUTE_ID),
        PRIMARY KEY (ISSUE_ID,ATTRIBUTE_ID,USER_ID)
);


