
# -----------------------------------------------------------------------
# SCARAB_OPTION_WORKFLOW
# -----------------------------------------------------------------------
drop table if exists SCARAB_OPTION_WORKFLOW;

CREATE TABLE SCARAB_OPTION_WORKFLOW
(
    FROM_OPTION_ID INTEGER NOT NULL,
    TO_OPTION_ID INTEGER NOT NULL,
    ROLE_NAME VARCHAR (255) NOT NULL,
    TRANSITION_RULE VARCHAR (255) NOT NULL,
    USER_ATTRIBUTE_ID INTEGER,
    MODULE_ID INTEGER NOT NULL,
    ISSUE_TYPE_ID INTEGER NOT NULL,
    PRIMARY KEY(FROM_OPTION_ID,TO_OPTION_ID,ROLE_NAME,MODULE_ID,ISSUE_TYPE_ID),
    FOREIGN KEY (ISSUE_TYPE_ID) REFERENCES SCARAB_ISSUE_TYPE (ISSUE_TYPE_ID),
    FOREIGN KEY (MODULE_ID) REFERENCES SCARAB_MODULE (MODULE_ID),
    FOREIGN KEY (USER_ATTRIBUTE_ID) REFERENCES SCARAB_ATTRIBUTE (ATTRIBUTE_ID),
    FOREIGN KEY (FROM_OPTION_ID) REFERENCES SCARAB_ATTRIBUTE_OPTION (OPTION_ID),
    FOREIGN KEY (TO_OPTION_ID) REFERENCES SCARAB_ATTRIBUTE_OPTION (OPTION_ID)
);
  
