package org.tigris.scarab.baseom.map;

// JDK classes
import java.util.*;
import java.math.*;

// Turbine classes
import org.apache.turbine.services.db.PoolBrokerService;
import org.apache.turbine.services.db.TurbineDB;
import org.apache.turbine.util.db.map.MapBuilder;
import org.apache.turbine.util.db.map.DatabaseMap;
import org.apache.turbine.util.db.map.TableMap;

/**
  *  This class was autogenerated by Torque on: 
  *
  * [Mon Feb 19 15:53:39 PST 2001]
  *
  */
public class AttributeValueMapBuilder implements MapBuilder
{
    /** the name of this class */
    public static final String CLASS_NAME = "org.tigris.scarab.baseom.map.AttributeValueMapBuilder";

    /** item */
    public static String getTable( )
    {
        return "SCARAB_ISSUE_ATTRIBUTE_VALUE";
    }


    /** SCARAB_ISSUE_ATTRIBUTE_VALUE.ISSUE_ID */
    public static String getAttributeValue_IssueId()
    {
        return getTable() + ".ISSUE_ID";
    }

    /** SCARAB_ISSUE_ATTRIBUTE_VALUE.ATTRIBUTE_ID */
    public static String getAttributeValue_AttributeId()
    {
        return getTable() + ".ATTRIBUTE_ID";
    }

    /** SCARAB_ISSUE_ATTRIBUTE_VALUE.OPTION_ID */
    public static String getAttributeValue_OptionId()
    {
        return getTable() + ".OPTION_ID";
    }

    /** SCARAB_ISSUE_ATTRIBUTE_VALUE.USER_ID */
    public static String getAttributeValue_UserId()
    {
        return getTable() + ".USER_ID";
    }

    /** SCARAB_ISSUE_ATTRIBUTE_VALUE.VALUE */
    public static String getAttributeValue_Value()
    {
        return getTable() + ".VALUE";
    }

    /** SCARAB_ISSUE_ATTRIBUTE_VALUE.DELETED */
    public static String getAttributeValue_Deleted()
    {
        return getTable() + ".DELETED";
    }

    /**  the database map  */
    private DatabaseMap dbMap = null;

    /**
        tells us if this DatabaseMapBuilder is built so that we don't have
        to re-build it every time
    */
    public boolean isBuilt()
    {
        if ( dbMap != null )
            return true;
        return false;
    }

    /**  gets the databasemap this map builder built.  */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }
    /** the doBuild() method builds the DatabaseMap */
    public void doBuild ( ) throws Exception
    {
        dbMap = TurbineDB.getDatabaseMap("default");

        dbMap.addTable(getTable());
        TableMap tMap = dbMap.getTable(getTable());

        tMap.setPrimaryKeyMethod(TableMap.NONE);



                  tMap.addForeignPrimaryKey ( getAttributeValue_IssueId(), new Integer(0) , "SCARAB_ISSUE" , "ISSUE_ID" );
          
                  tMap.addForeignPrimaryKey ( getAttributeValue_AttributeId(), new Integer(0) , "SCARAB_ATTRIBUTE" , "ATTRIBUTE_ID" );
          
                  tMap.addForeignKey ( getAttributeValue_OptionId(), new Integer(0) , "SCARAB_ATTRIBUTE_OPTION" , "OPTION_ID" );
          
                  tMap.addForeignKey ( getAttributeValue_UserId(), new Integer(0) , "TURBINE_USER" , "USER_ID" );
          
                  tMap.addColumn ( getAttributeValue_Value(), new String() );
          
                  tMap.addColumn ( getAttributeValue_Deleted(), new Integer(0) );
          
    }

}
