package org.tigris.scarab.baseom.map;

// JDK classes
import java.util.*;
import java.math.*;

// Turbine classes
import org.apache.turbine.services.db.PoolBrokerService;
import org.apache.turbine.services.db.TurbineDB;
import org.apache.turbine.util.db.map.MapBuilder;
import org.apache.turbine.util.db.map.DatabaseMap;
import org.apache.turbine.util.db.map.TableMap;

/**
  *  This class was autogenerated by Torque on: 
  *
  * [Mon Feb 19 15:53:39 PST 2001]
  *
  */
public class AttributeMapBuilder implements MapBuilder
{
    /** the name of this class */
    public static final String CLASS_NAME = "org.tigris.scarab.baseom.map.AttributeMapBuilder";

    /** item */
    public static String getTable( )
    {
        return "SCARAB_ATTRIBUTE";
    }


    /** SCARAB_ATTRIBUTE.ATTRIBUTE_ID */
    public static String getAttribute_AttributeId()
    {
        return getTable() + ".ATTRIBUTE_ID";
    }

    /** SCARAB_ATTRIBUTE.ATTRIBUTE_NAME */
    public static String getAttribute_Name()
    {
        return getTable() + ".ATTRIBUTE_NAME";
    }

    /** SCARAB_ATTRIBUTE.ATTRIBUTE_TYPE_ID */
    public static String getAttribute_TypeId()
    {
        return getTable() + ".ATTRIBUTE_TYPE_ID";
    }

    /** SCARAB_ATTRIBUTE.DELETED */
    public static String getAttribute_Deleted()
    {
        return getTable() + ".DELETED";
    }

    /**  the database map  */
    private DatabaseMap dbMap = null;

    /**
        tells us if this DatabaseMapBuilder is built so that we don't have
        to re-build it every time
    */
    public boolean isBuilt()
    {
        if ( dbMap != null )
            return true;
        return false;
    }

    /**  gets the databasemap this map builder built.  */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }
    /** the doBuild() method builds the DatabaseMap */
    public void doBuild ( ) throws Exception
    {
        dbMap = TurbineDB.getDatabaseMap("default");

        dbMap.addTable(getTable());
        TableMap tMap = dbMap.getTable(getTable());

        tMap.setPrimaryKeyMethod(TableMap.IDBROKERTABLE);

        tMap.setPrimaryKeyMethodInfo(tMap.getName());


                  tMap.addPrimaryKey ( getAttribute_AttributeId(), new Integer(0) );
          
                  tMap.addColumn ( getAttribute_Name(), new String() );
          
                  tMap.addForeignKey ( getAttribute_TypeId(), new Integer(0) , "SCARAB_ATTRIBUTE_TYPE" , "ATTRIBUTE_TYPE_ID" );
          
                  tMap.addColumn ( getAttribute_Deleted(), new Integer(0) );
          
    }

}
