package org.tigris.scarab.baseom.map;

// JDK classes
import java.util.*;
import java.math.*;

// Turbine classes
import org.apache.turbine.services.db.PoolBrokerService;
import org.apache.turbine.services.db.TurbineDB;
import org.apache.turbine.util.db.map.MapBuilder;
import org.apache.turbine.util.db.map.DatabaseMap;
import org.apache.turbine.util.db.map.TableMap;

/**
  *  This class was autogenerated by Torque on: 
  *
  * [Mon Feb 19 15:53:39 PST 2001]
  *
  */
public class RModuleUserMapBuilder implements MapBuilder
{
    /** the name of this class */
    public static final String CLASS_NAME = "org.tigris.scarab.baseom.map.RModuleUserMapBuilder";

    /** item */
    public static String getTable( )
    {
        return "SCARAB_R_MODULE_USER";
    }


    /** SCARAB_R_MODULE_USER.MODULE_ID */
    public static String getRModuleUser_ModuleId()
    {
        return getTable() + ".MODULE_ID";
    }

    /** SCARAB_R_MODULE_USER.USER_ID */
    public static String getRModuleUser_UserId()
    {
        return getTable() + ".USER_ID";
    }

    /** SCARAB_R_MODULE_USER.DELETED */
    public static String getRModuleUser_Deleted()
    {
        return getTable() + ".DELETED";
    }

    /**  the database map  */
    private DatabaseMap dbMap = null;

    /**
        tells us if this DatabaseMapBuilder is built so that we don't have
        to re-build it every time
    */
    public boolean isBuilt()
    {
        if ( dbMap != null )
            return true;
        return false;
    }

    /**  gets the databasemap this map builder built.  */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }
    /** the doBuild() method builds the DatabaseMap */
    public void doBuild ( ) throws Exception
    {
        dbMap = TurbineDB.getDatabaseMap("default");

        dbMap.addTable(getTable());
        TableMap tMap = dbMap.getTable(getTable());

        tMap.setPrimaryKeyMethod(TableMap.NONE);



                  tMap.addForeignPrimaryKey ( getRModuleUser_ModuleId(), new Integer(0) , "SCARAB_MODULE" , "MODULE_ID" );
          
                  tMap.addForeignPrimaryKey ( getRModuleUser_UserId(), new Integer(0) , "TURBINE_USER" , "USER_ID" );
          
                  tMap.addColumn ( getRModuleUser_Deleted(), new Integer(0) );
          
    }

}
