package org.tigris.scarab.baseom.map;

// JDK classes
import java.util.*;
import java.math.*;

// Turbine classes
import org.apache.turbine.services.db.PoolBrokerService;
import org.apache.turbine.services.db.TurbineDB;
import org.apache.turbine.util.db.map.MapBuilder;
import org.apache.turbine.util.db.map.DatabaseMap;
import org.apache.turbine.util.db.map.TableMap;

/** This class was autogenerated by GenerateMapBuilder on: Wed Feb 07 17:08:09 PST 2001 */
public class ScarabAttributeMapBuilder implements MapBuilder
{
    /** the name of this class */
    public static final String CLASS_NAME = "org.tigris.scarab.baseom.map.ScarabAttributeMapBuilder";

    /** item */
    public static String getTable( )
    {
        return "SCARAB_ATTRIBUTE";
    }


    /** SCARAB_ATTRIBUTE.ATTRIBUTE_ID */
    public static String getScarabAttribute_AttributeId()
    {
        return getTable() + ".ATTRIBUTE_ID";
    }

    /** SCARAB_ATTRIBUTE.ATTRIBUTE_NAME */
    public static String getScarabAttribute_Name()
    {
        return getTable() + ".ATTRIBUTE_NAME";
    }

    /** SCARAB_ATTRIBUTE.ATTRIBUTE_TYPE_ID */
    public static String getScarabAttribute_TypeId()
    {
        return getTable() + ".ATTRIBUTE_TYPE_ID";
    }

    /** SCARAB_ATTRIBUTE.DELETED */
    public static String getScarabAttribute_Deleted()
    {
        return getTable() + ".DELETED";
    }


    /**  the database map  */
    private DatabaseMap dbMap = null;

    /**
        tells us if this DatabaseMapBuilder is built so that we don't have
        to re-build it every time
    */
    public boolean isBuilt()
    {
        if ( dbMap != null )
            return true;
        return false;
    }

    /**  gets the databasemap this map builder built.  */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }
    /** the doBuild() method builds the DatabaseMap */
    public void doBuild ( ) throws Exception
    {
        dbMap = TurbineDB.getDatabaseMap("defauult");

        dbMap.addTable(getTable());
        TableMap tMap = dbMap.getTable(getTable());

        tMap.setPrimaryKeyMethod(TableMap.IDBROKERTABLE);



                  tMap.addPrimaryKey ( getScarabAttribute_AttributeId(), new Integer(0) );
          
                  tMap.addColumn ( getScarabAttribute_Name(), new String() );
          
                  tMap.addForeignKey ( getScarabAttribute_TypeId(), new Integer(0) , "SCARAB_ATTRIBUTE_TYPE" , "ATTRIBUTE_TYPE_ID" );
          
                  tMap.addColumn ( getScarabAttribute_Deleted(), new Integer(0) );
          
    }

}
