package org.tigris.scarab.baseom.map;

// JDK classes
import java.util.*;
import java.math.*;

// Turbine classes
import org.apache.turbine.services.db.PoolBrokerService;
import org.apache.turbine.services.db.TurbineDB;
import org.apache.turbine.util.db.map.MapBuilder;
import org.apache.turbine.util.db.map.DatabaseMap;
import org.apache.turbine.util.db.map.TableMap;

/** This class was autogenerated by GenerateMapBuilder on: Wed Feb 07 17:08:09 PST 2001 */
public class ScarabActivityMapBuilder implements MapBuilder
{
    /** the name of this class */
    public static final String CLASS_NAME = "org.tigris.scarab.baseom.map.ScarabActivityMapBuilder";

    /** item */
    public static String getTable( )
    {
        return "SCARAB_ACTIVITY";
    }


    /** SCARAB_ACTIVITY.ISSUE_ID */
    public static String getScarabActivity_IssueId()
    {
        return getTable() + ".ISSUE_ID";
    }

    /** SCARAB_ACTIVITY.ATTRIBUTE_ID */
    public static String getScarabActivity_AttributeId()
    {
        return getTable() + ".ATTRIBUTE_ID";
    }

    /** SCARAB_ACTIVITY.TRANSACTION_ID */
    public static String getScarabActivity_TransactionId()
    {
        return getTable() + ".TRANSACTION_ID";
    }

    /** SCARAB_ACTIVITY.OLD_VALUE */
    public static String getScarabActivity_OldValue()
    {
        return getTable() + ".OLD_VALUE";
    }

    /** SCARAB_ACTIVITY.NEW_VALUE */
    public static String getScarabActivity_NewValue()
    {
        return getTable() + ".NEW_VALUE";
    }


    /**  the database map  */
    private DatabaseMap dbMap = null;

    /**
        tells us if this DatabaseMapBuilder is built so that we don't have
        to re-build it every time
    */
    public boolean isBuilt()
    {
        if ( dbMap != null )
            return true;
        return false;
    }

    /**  gets the databasemap this map builder built.  */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }
    /** the doBuild() method builds the DatabaseMap */
    public void doBuild ( ) throws Exception
    {
        dbMap = TurbineDB.getDatabaseMap("defauult");

        dbMap.addTable(getTable());
        TableMap tMap = dbMap.getTable(getTable());

        tMap.setPrimaryKeyMethod(TableMap.NONE);



                  tMap.addForeignPrimaryKey ( getScarabActivity_IssueId(), new Integer(0) , "SCARAB_ISSUE" , "ISSUE_ID" );
          
                  tMap.addForeignPrimaryKey ( getScarabActivity_AttributeId(), new Integer(0) , "SCARAB_ATTRIBUTE" , "ATTRIBUTE_ID" );
          
                  tMap.addForeignPrimaryKey ( getScarabActivity_TransactionId(), new Integer(0) , "SCARAB_TRANSACTION" , "TRANSACTION_ID" );
          
                  tMap.addColumn ( getScarabActivity_OldValue(), new String() );
          
                  tMap.addColumn ( getScarabActivity_NewValue(), new Double(0) );
          
    }

}
