package org.tigris.scarab.baseom.map;

// JDK classes
import java.util.*;
import java.math.*;

// Turbine classes
import org.apache.turbine.services.db.PoolBrokerService;
import org.apache.turbine.services.db.TurbineDB;
import org.apache.turbine.util.db.map.MapBuilder;
import org.apache.turbine.util.db.map.DatabaseMap;
import org.apache.turbine.util.db.map.TableMap;

/** This class was autogenerated by GenerateMapBuilder on: Mon Jan 08 11:17:17 PST 2001 */
public class ScarabRModuleUserRoleMapBuilder implements MapBuilder
{
    /** the name of this class */
    public static final String CLASS_NAME = "org.tigris.scarab.baseom.map.ScarabRModuleUserRoleMapBuilder";

    /** item */
    public static String getTable( )
    {
        return "SCARAB_R_MODULE_USER_ROLE";
    }


    /** SCARAB_R_MODULE_USER_ROLE.MODULE_ID */
    public static String getScarabRModuleUserRole_ModuleId()
    {
        return getTable() + ".MODULE_ID";
    }

    /** SCARAB_R_MODULE_USER_ROLE.USER_ID */
    public static String getScarabRModuleUserRole_UserId()
    {
        return getTable() + ".USER_ID";
    }

    /** SCARAB_R_MODULE_USER_ROLE.ROLE_ID */
    public static String getScarabRModuleUserRole_RoleId()
    {
        return getTable() + ".ROLE_ID";
    }

    /** SCARAB_R_MODULE_USER_ROLE.DELETED */
    public static String getScarabRModuleUserRole_Deleted()
    {
        return getTable() + ".DELETED";
    }


    /**  the database map  */
    private DatabaseMap dbMap = null;

    /**
        tells us if this DatabaseMapBuilder is built so that we don't have
        to re-build it every time
    */
    public boolean isBuilt()
    {
        if ( dbMap != null )
            return true;
        return false;
    }

    /**  gets the databasemap this map builder built.  */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }
    /** the doBuild() method builds the DatabaseMap */
    public void doBuild ( ) throws Exception
    {
        dbMap = TurbineDB.getDatabaseMap("default");

        dbMap.addTable(getTable());
        TableMap tMap = dbMap.getTable(getTable());

        tMap.setPrimaryKeyMethod(tMap.NONE);



                  tMap.addForeignPrimaryKey ( getScarabRModuleUserRole_ModuleId(), new Integer(0) , "SCARAB_R_MODULE_USER" , "MODULE_ID" );
          
                  tMap.addForeignPrimaryKey ( getScarabRModuleUserRole_UserId(), new Integer(0) , "SCARAB_R_MODULE_USER" , "USER_ID" );
          
                  tMap.addPrimaryKey ( getScarabRModuleUserRole_RoleId(), new Integer(0) );
          
                  tMap.addColumn ( getScarabRModuleUserRole_Deleted(), new Integer(0) );
          
    }

}
